### ISSUE TITLE
*QUESTION*: Feature Suggestion

### ISSUE THREAD

**Issue by tylermav** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#10]
**Describe your suggestion.**
Any known compatibility issues with other biome-generation mods?

**Additional context**
Did not see info on this on the front page.

Beautiful mod btw! Thank you!

**Comment by UHQ-GAMES** [comment]
basically all of the big ones it should work no problem but i cant guarantee compat with all of them. best thing to do is to try it out and if you run into issues feel free to post here again!

**Comment by tylermav** [comment]
Thank you very much! 

I also went on to ya'lls Discord on saw that information on there too!
