### ISSUE TITLE
Crash between Ars Nouvea and Regions Unexplored

### ISSUE THREAD

**Issue by Kaligraphy22** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#100]
**Describe the bug**
The game crashes when using a timer turret to grow duskmelons from Regions Unexplored.

So this one's a bit odd. If I use a Timer turret with [Touch > Grow] spell on a duskmelon from Regions Unexplored, it crashes the game after the spell fires like 2-3 times. However, I don't crash when I use [Touch > Grow] from my spell book. I was using the Creative Spell book in a test world. The dusk melon is planted and grows like a sweet berry bush. At the time, I did not test the other possible turrets. Fair warning, if you successfully reproduce this setup, that world will crash and you'll be unable to get back into it.

Upon further testing, this crash occurs with any kind of Ars turret using the spell mentioned above. The exact point when it crashes is when the plant is fully grown and receives another cast of [Touch > Grow] specifically from a turret, the game crashes immediately. I assumed the duskmelon acts the same as sweet berry bush. "Grow" is just a bonemeal effect from Ars. I've talked to the folks at the Ars Nouveau discord and they said the fault might be on your end.

A snippet of what I was told: "Grow is simply calling a bone meal interaction and the crop goes out of bounds, which should have been guarded against in the crop code."

**Crash Logs**
https://mclo.gs/aYmL8t8

**How To Reproduce**
Steps to reproduce the bug:
1. Get a timer turret and grab a full source jar. Aim at the duskmelon plant from any angle. I chose from straight above.
2. Add [Touch > Grow] to the turret.
3. Watch the turret fire at the plant. It will grow the plant in like 1-2 casts.
4. Watch your game freeze, then crash and kiss that world goodbye.

**Versions**
Launcher: Prism Launcher 8.0
Minecraft version: 1.20.1
Forge version: Neoforge 47.1.79
Ars Nouveau version: ars_nouveau-1.20.1-4.8.1-all.jar
Regions Unexplored version: RegionsUnexploredForge-0.5.3+1.20.1.jar

**Screenshots**
I have no videos of my test worlds crashing, sorry.

**Comment by UHQ-GAMES** [comment]
thanks, ill look closer into this when i have a chance

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 7c6d724ca791bc5a024ba0475f31b63c848e1fbd
