### ISSUE TITLE
Mycotoxic moss and mytoxic daisy are non-renewable

### ISSUE THREAD

**Issue by TheDeviantCrafter** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#102]
**Describe your suggestion.**
1. Mycotoxic moss should replace nearby netherrack when bone meal is applied. It does create bone meal particles on netherrack so this might be intended but bugged.
2. Applying bone meal spawn mycotoxic grass and mushrooms, but no mycotoxic daisies. That should be changed.

**Comment by UHQ-GAMES** [comment]
the daisy should be bonemealable to create copies like other tall plants, if its not then that's an oversight on my end. however the Mycotoxic Moss is spreadable the same way vanilla Nyliums are, just bonemeal the adjacent Netherrack block to spread

**Comment by TheDeviantCrafter** [comment]
Applying bone meal spawns particles on nearby netherrack but nothing actually converts.

**Comment by TheDeviantCrafter** [comment]
I get the same issue when trying to grow stone buds in the baobab savanna biome. Applying bone meal to grass next to terracotta creates particles like its trying to grow stone buds, but they don't appear.

**Comment by UHQ-GAMES** [comment]
pinning this as im gonna tinker with this in the near future, closing for now
