### ISSUE TITLE
Dusktrap spreads after it gets a kill

### ISSUE THREAD

**Issue by TheDeviantCrafter** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#104]
**Describe your suggestion.**
When a dusktrap plant kills a mob, it has a chance to place another dusk trap in a 3x3 area around it. 

**Additional context**
Bone meal wouldn't make sense since dusktraps are apparently carnivores. This seems like a more fun way to farm dusktraps than adding a seed. 

Limiting spread to a 3x3 area would make it easy to block spawns for a mob grinder or trap.

**Comment by UHQ-GAMES** [comment]
hmm thats actually a cool idea, i might tinker with that to see if it works or not

**Comment by UHQ-GAMES** [comment]
pinning this and closing for future use
