### ISSUE TITLE
Viridescent Nylium not bonemealing

### ISSUE THREAD

**Issue by DreadlordRhayth** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#105]
Describe your suggestion.
Would be awesome if we could spread Viridescent Nylium with bonemeal

**Comment by UHQ-GAMES** [comment]
might be an oversight on my side but it should be?

**Comment by DreadlordRhayth** [comment]
I'm playing on 1.20.1, and can confirm nothing happens when bonemeal is used on the viridescent nylium, I can spread others like prismoss etc. So I assume everything is working on my end

**Comment by UHQ-GAMES** [comment]
Ok thanks for check I'll mark it be fixed

**Comment by UHQ-GAMES** [comment]
added in 5f7a5fac8b737c7f89be468c6e9e51c306ac211d
