### ISSUE TITLE
Ensure that all grasses and flowers appear when applying bone meal to grass in the correct biome

### ISSUE THREAD

**Issue by TheDeviantCrafter** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#106]
**Describe your suggestion.**
There are several small plants that appear to be non-renewable. Applying bone meal to grass should spawn all of the grass/flower blocks in that biome.

So far I've noticed that these do not appear:
- Aster
- Barley
- Elephant ear
- Dead steppe shrub
- Small desert shrub

Barley would need to be fairly uncommon since it can be smelted into bread. If it takes around 8 bone meal to get a barley, farming bread this way would be on par with using bone meal on wheat.

**Additional context**
This would keep the mod consistent with vanilla mechanics, and give builders more plants to work with.

**Comment by UHQ-GAMES** [comment]
these are mostly intentional as I want Aster, Steppe Shrubs and Desert Shrubs to be non renewable. As for Elephant Ear and Barley, sadly Minecraft bone meal feature isn't good at handling double tall plants, maybe ill make a way to renew those but that will be for the future

**Comment by UHQ-GAMES** [comment]
pinning this as I may revisit this in the future
