### ISSUE TITLE
Barrel cactus plants spread when given bone meal

### ISSUE THREAD

**Issue by TheDeviantCrafter** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#107]
**Describe your suggestion.**
Giving a barrel cactus bone meal will spread spawn 1-3 more barrel cactus plants nearby. They can spawn in a 5x5x3 area, with a preference for the 3x3x1 area next to the cactus.

Technically barrel cactus plants propagate with seeds in real life, but players expect crops to have a survival benefit worth farming. Many cacti reproduce by budding.

They could also appear when applying bone meal to grass, but the player would have to bring their own grass to the desert which seems odd.

**Additional context**
Add any pictures, screenshots, or other relevant information about the suggestion here.

**Comment by UHQ-GAMES** [comment]
i like this idea, theres definitely something here i could do in a future update! im gonna pin this and close it to keep things organized but im gonna write this down for future use!
