### ISSUE TITLE
Too many flowers

### ISSUE THREAD

**Issue by Nafiaren** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#108]
Hey, sorry for disturbing, 
I just wanted to ask if there is a way to make the biomes have less flowers? As of now, if we are traversing through the world and we find some biomes from "Regions Unexplored" they are just absolutely packed with flowers to the point, that there aren't even blocks, that don't countain flowers on top of them, which of course, while playing on a server with my friends causes a lot of lag..
So if there is a way to make the flowers only 50% as much as they are now, i would gladly appreciate your help!

**Comment by UHQ-GAMES** [comment]
it can definitely be achieved with a datapack that modifies the flowers spawn chance. maybe ill make something like that in the future in the little free time i have. in the meantime it may be something you can do yourself if you know your way around datapacks

**Comment by UHQ-GAMES** [comment]
gonna pin this and close it to keep things organized but i have it written down as a possible future datapack
