### ISSUE TITLE
Magnolia Hanging Sign breaks/crashes the game.

### ISSUE THREAD

**Issue by kunoleo** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#109]
**Describe the bug**
_I've got some more mods installed, might be the reason the sign acts up, not tested this without the other mods._
When placing this item Minecraft crashes and gives you the "ERROR, Game crashed" screen.
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/131197971/c0d70889-fb31-4b3f-a5e3-4356e5977978)

**Crash Logs**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/131197971/ff89ec54-d675-4b10-b296-e15fe505ffa0)
[crash-2024-01-19_13.38.57-client.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13989089/crash-2024-01-19_13.38.57-client.txt)

**How To Reproduce**
Placing the sign and being close to it. if a player gets to close to the sign so "it spawns in" they will crash too.

**Version**
Minecraft Version:
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/131197971/591f31c3-52a5-4193-bd4d-9088dded46fa)

Mod Version:
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/131197971/bb16f5a9-7b7d-43c0-962e-9263bcf7b756)

**Comment by KirboSoftware** [comment]
Do you have a crash log? Would be very useful thank you very much. As this doesn't tell us anything.

**Comment by kunoleo** [comment]
You mean "view crash report"? I don't know where I'd find th ecrash log. I'm very new to this stuff.

**Comment by kunoleo** [comment]
> Do you have a crash log? Would be very useful thank you very much. As this doesn't tell us anything.

You mean "view crash report"? I don't know where I'd find th ecrash log. I'm very new to this stuff.

**Comment by UHQ-GAMES** [comment]
were getting back into the swing of things, we'll take a closer look into this

**Comment by KirboSoftware** [comment]
This issue should be resolved in 0.5.4
