### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by FuturisticDruid** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#11]
**Describe the bug**
Sculkwood sign crashes game when placed in world

**Crash Logs**
[crash-2023-07-26_18.24.02-client.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12177864/crash-2023-07-26_18.24.02-client.txt)

**How To Reproduce**
Steps to reproduce the bug: place Sculkwood sign in world

**Version**
Minecraft Version: 1.20.1

Modloader Version: Fabric 0.14.21

Mod Version: 4.1

**Comment by FuturisticDruid** [comment]
update: according to someone else that is helping test things it is all of the signs not just the sculkwood

**Comment by UHQ-GAMES** [comment]
ill pass it on to my fabric team, thanks!

**Comment by Zunwolf1896** [comment]
We figured out having the Epic Knights mod isntalled was causing these crashes, I have linked the bugs together.

**Comment by JoostMSoftware** [comment]
@Zunwolf1896 Hello, I'm part of the fabric team from Regions Unexplored. Is there more knowledge about the specific compat issue? Besides well, that the sign renderer is being messed up when having the 2 mods together.

**Comment by JoostMSoftware** [comment]
The compat issue is resolved with epic knights!
