### ISSUE TITLE
Mud + leaves = peat

### ISSUE THREAD

**Issue by TheDeviantCrafter** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#110]
**Describe your suggestion.**
Real life peat is made of partially decomposed plant matter. Mixing mud with fresh leaves would get you close enough for Minecraft's standards. I suggest two shapeless recipes:

Mud block + any leaf block = peat block

Peat block + dirt = 2 peat dirt

**Additional context**
Vanilla mud blocks are renewable. This would make all forms of peat renewable by extension.

**Comment by UHQ-GAMES** [comment]
ooh i like this idea! ill definitely put it on the roadmap!

**Comment by UHQ-GAMES** [comment]
pinned for future use
