### ISSUE TITLE
Duskmelons growing on Rich Soil crashes the game

### ISSUE THREAD

**Issue by BlossomZZ** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#111]
Minecraft Version: 1.19.2

Modloader Version: Forge 43.3.7

Mod Version: 0.5.3+1.19.2.jar
![2024-01-24](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/141999786/b8fd5c61-2ad9-45d0-8220-bcbceb6e7be7)

**Comment by UHQ-GAMES** [comment]
thanks! will fix for 0.5.4

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 7c6d724ca791bc5a024ba0475f31b63c848e1fbd
