### ISSUE TITLE
Issue with Overgrown Bone Block

### ISSUE THREAD

**Issue by roocx** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#112]
Hi i'm french, sorry for my bad english.
I noticed that we can have infinite bonemeal by crafting the overgrown bone block: it require 4 bonemeal to craft one, then we can place the block and break it to have a bone block and craft 9 bonemeal. 
We can finally make 9 bonemeal out of 4.

ps: this is a very great mod, i like it a lot, you make a very good job ! ;)

Minecraft Version: 1.20.1

Modloader Version: Forge 47.2.0

Mod Version: v0.5.3.1

**Comment by KirboSoftware** [comment]
this dupe has been mentioned before, however I don't know if it will be included in the mega patch for regions soon. @UHQ-GAMES what's your say in this? intended behavior or dupe glitch?

**Comment by UHQ-GAMES** [comment]
definitely not intentional, will fix for 0.5.4

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 32f5096318cab3d61abb3176c441f9472bbd6031
