### ISSUE TITLE
Chalk brick issue

### ISSUE THREAD

**Issue by roocx** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#113]
The Chalk Brick doesn't have specified tool to break it.
Trying to break it with diamond pickaxe take a while and doesn't drop the block.

Minecraft Version: 1.20.1

Modloader Version: Forge 47.2.0

Mod Version: v0.5.3.1

**Comment by UHQ-GAMES** [comment]
seems to extend to slabs and stairs too, will fix for next version!

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 dea180bb004adc3c6e5e73fc8058be7e1d3bf5c8
