### ISSUE TITLE
skulk back into the mod

### ISSUE THREAD

**Issue by 610610gg** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#114]
dear regions unexplored creator/s,

my request is to re-add the sculkwood set because it is my favourite wood set and i'm sad to discover just now that the 0.5.0 update removed it so i would like to use later updates with the sculkwood in 1.20.1.

thank you for listening.

**Comment by UHQ-GAMES** [comment]
hey! I'm planning to bring these back in a separate mod in the future! ill mark this as complete as I've already got it in the works
