### ISSUE TITLE
Random startup carsh: "error during the common_setup event phase"

### ISSUE THREAD

**Issue by DezZzO** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#115]
**Describe the bug**
Startup will fail sometimes. Approximately once per 10 launches, it's random, even if I don't do any changes to config files or add/remove mods at all.

**Crash Logs**
https://pastebin.com/956KP8ZB

**How To Reproduce**
No idea, sorry, it is totally random for me.

**Version**
Minecraft Version: 1.19.2

Modloader Version: Forge 43.3.7

Mod Version: RegionsUnexploredForge-0.5.3+1.19.2.jar

**Screenshots**
Error example screenshot provided below. 
Second mod seems to error due to the same reason and this crash will happen even if I remove it, it doesn't seem to be a conflict between them.
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/19258658/cbc4481f-a857-4cb5-971a-b934894ff734)

**Comment by UHQ-GAMES** [comment]
hmm that is odd but it might be modernfix conflicting with the two mods? its mentioned in the log you attached, if you can report this to modernfix devs as well then maybe we can find the issue
