### ISSUE TITLE
Broken ore generation 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#117]
Minecraft 1.19.2
Forge 43.3.5 

Accumulation of ores in huge quantities
Terralith_1.19.3_v2.3.12.jar + RegionsUnexploredForge-0.5.3+1.19.2.jar + TerraBlender-forge-1.19.2-2.0.1.166.jar

![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/15a9b311-173a-4723-8826-bca7f825d597)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/023fcd9a-fc8c-4537-b03a-4df2e874d9f2)

**Comment by UHQ-GAMES** [comment]
this is a vanilla feature, more info linked below

https://minecraft.wiki/w/Ore_vein
