### ISSUE TITLE
Small Oak Logs can be stripped indefinitely

### ISSUE THREAD

**Issue by Mrthomas20121** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#118]
**Describe the bug**
Small Oak Logs can be stripped indefinitely.

**Crash Logs**
No Crash

**How To Reproduce**
Steps to reproduce the bug:

take an axe, right click on a small oak log to convert it to stripped small oak log, once converted, you can do it again but it doesn't change the blockstate, it just consume durability.

**Version**
Minecraft Version: 1.20.1

Modloader Version: Forge 1.20.1-47.1.3

Mod Version: 0.5.3.1

**Screenshots**

**Comment by UHQ-GAMES** [comment]
thanks, will have a look into it

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 ba84b6d8f773cabfc457296bcee39749bc016156
