### ISSUE TITLE
Broken Leaf Pile Texture

### ISSUE THREAD

**Issue by mxnmnm** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#119]
**Describe the bug**
Enchanted birch leaf piles can have a missing texture under certain conditions

**Log**
https://gist.github.com/mxnmnm/5462c46e15712d11e6683d784f499228

**How To Reproduce**
Go to mauve hills biome (it doesn't work in all biomes and this is the one where I noticed the issue)
Place an enchanted birch leaf pile with 3 leaves

**Version**
Minecraft Version: 1.20.1

Modloader Version: neoforge 47.1.84

Mod Version: 0.5.3.1

**Screenshots**
![2024-02-09_06 53 47](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/8508976/a9e3c195-ef95-4842-879f-01ffe9d1f878)

**Comment by UHQ-GAMES** [comment]
hmm thats odd, doesnt seem to happen when the mods on its own, maybe somehow another mod is causing it? doesnt seem to mention it in the log either

**Comment by UHQ-GAMES** [comment]
sadly I'm not able to replicate this, best I can say is make sure everything including mods, loader, drivers etc. are up to date.

**Comment by mxnmnm** [comment]
I can't recreate it either and it happened with other vanilla blocks in specific worlds so I honestly don't know... Probably not this mod tho considering it happened to other vanilla blocks

**Comment by UHQ-GAMES** [comment]
yeaa if i had more info id give it to ya but sadly i cant find any info on it
