### ISSUE TITLE
Conflict w/ Tails and Trails backport 1.18.2

### ISSUE THREAD

**Issue by Lozf** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#12]
**Describe the bug**
Loading both results in crashing with multiple entries for Cherry.  https://www.curseforge.com/minecraft/mc-mods/onetwenty-1-20-backport.  I opened an issue with them earlier this month and only tracked down the conflict today when I had some time.  https://legacy.curseforge.com/minecraft/mc-mods/onetwenty-1-20-backport/issues/5

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error. 
https://gist.github.com/Lozf/c449b12ca104b06f97fcc0155cce19f7

**How To Reproduce**
Steps to reproduce the bug:  Have both, it crashes during game loading.

**Version**
Minecraft Version: 1.18.2

Modloader Version: 40.2.4

Mod Version: both at the latest versions for 1.18.2

**Screenshots**

**Comment by UHQ-GAMES** [comment]
hey there, hmm this is odd because the signs are registered under the regions unexplored namespace so in theory that crash shouldnt be possible. I dont support 1.18.2 anymore but ill check it out and see if its something that i can easily fix. thanks!

**Comment by Lozf** [comment]
Thank you for looking into it!

**Comment by UHQ-GAMES** [comment]
Ive put it on the todo list if we ever do another update for 1.18.2 but as for now were already pretty overwhelmed with the other projects being done.
