### ISSUE TITLE
Planks cannot be crafted from logs

### ISSUE THREAD

**Issue by Daimon6453** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#121]
**Describe the bug**
Wood planks cannot be crafted from logs, and the recipe doesn't show up in Just Enough Items.

**How To Reproduce**
Steps to reproduce the bug: 
- Install all versions listed below along with latest version of JEI
- Open New World
- attempt to craft planks from the mod
- planks cannot be crafted

**Version**
Minecraft Version: 1.20.1

Modloader Version: Forge 47.2.20

Mod Version: 0.5.3.1

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/114356114/0659e6de-67bb-4563-af1a-f2bf57834c44)
(maple planks JEI recipes)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/114356114/93bfbd5e-3670-4774-b6ea-ef1cd2cefefd) 
(attempting to craft maple planks)

**Comment by KirboSoftware** [comment]
What are you using for this? Can we have a log for this and also the pack you're using to get this issue?

**Comment by Daimon6453** [comment]
Here's the latest log file:
[latest.zip](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/14324543/latest.zip)

And the (long) modlist (there's an assortment of mods downloaded from modrinth and curseforge) (sorry in advance):
	- ae2 15.0.21
	- ae2wtlib 15.2.1-forge
	- aeroblender 1.20.1-1.0.1-neoforge
	- aether 1.20.1-1.2.0-neoforge
	- aiimprovements 0.5.2
	- alchemistry 2.3.4
	- alchemylib 1.0.30
	- almostunified 1.20.1-0.7.2
	- alternate_current 1.7.0
	- another_furniture 1.20.1-3.0.1
	- appleskin 2.5.1+mc1.20.1
	- appmek 1.4.2
	- aquaculture 2.5.1
	- aquaculturedelight 1.0.0
	- archers_paradox 5.0.0
	- architects_palette 1.3.6.1
	- architectury 9.1.13
	- armorstatues 8.0.5
	- ars_creo 4.0.1
	- ars_elemental 1.20.1-0.6.4.1
	- ars_nouveau 4.9.0
	- arseng 1.1.5
	- artifacts 9.2.2
	- athena 3.1.1
	- attributefix 21.0.4
	- balanced_crates 1.7.71
	- balm 7.2.1
	- barteringstation 8.0.0
	- bcc 4.0.8
	- betteradvancements 0.3.2.162
	- betterarcheology 1.1.5-1.20.1
	- betterchunkloading 1.20.1-3.3
	- bettercombat 1.8.4+1.20.1
	- betterdeserttemples 1.20-Forge-3.0.3
	- betterdungeons 1.20-Forge-4.0.3
	- betterendisland 1.20-Forge-2.0.5
	- betterf3 7.0.2
	- betterfortresses 1.20-Forge-2.0.5
	- betterfpsdist 1.20.1-4.2
	- betterjungletemples 1.20-Forge-2.0.4
	- bettermineshafts 1.20-Forge-4.0.4
	- betteroceanmonuments 1.20-Forge-3.0.4
	- betterstrongholds 1.20-Forge-4.0.3
	- betterthirdperson 1.9.0
	- betterwitchhuts 1.20-Forge-3.0.3
	- bookshelf 20.1.9
	- botanypots 13.0.23
	- botanytrees 9.0.9
	- botarium 2.3.3
	- bountiful 6.0.3+1.20.1
	- buildersaddition 1.20.1-20230928a
	- buildersdelight 1.2
	- bwncr 3.17.0
	- cabletiers 1.20.1-1.2.2
	- caelus 3.1.0+1.20
	- cfm 7.0.0-pre36
	- chalk 1.6.3
	- charginggadgets 1.11.0
	- charmofundying 6.4.5+1.20.1
	- chat_heads 0.10.31
	- chefsdelight 1.0.3-forge-1.20.1
	- chemlib 2.0.18
	- cherishedworlds 6.1.4+1.20.1
	- chimes 2.0.1
	- chipped 3.0.4
	- chunksending 1.20.1-2.8
	- cleanswing 1.20-1.5
	- cloth_config 11.1.118
	- clumps 12.0.0.3
	- cobblefordays 1.8.0
	- cofh_core 11.0.0
	- comforts 6.3.5+1.20.1
	- commoncapabilities 2.9.1
	- connectedglass 1.1.11
	- connectivity 1.20.1-4.9
	- constructionwand 1.20.1-2.11
	- controlling 12.0.2
	- cosmeticarmorreworked 1.20.1-v1a
	- cozy 1.1.1
	- craftingtweaks 18.2.2
	- create 0.5.1.f
	- create_crush_everything 1.0.2
	- create_dragon_lib 1.3.3
	- create_enchantment_industry 1.2.7.h
	- create_sa 2.0.4.
	- createaddition 1.20.1-1.2.3
	- createappliedkinetics 1.3.2-1.20.1
	- createdeco 2.0.1-1.20.1-forge
	- createframed 1.2
	- cristellib 1.1.5
	- croptopia 3.0.4
	- croptopia_additions 2.0.0
	- croptopia_delight 1.0
	- cucumber 7.0.7
	- cumulus_menus 1.20.1-1.0.0-neoforge
	- cupboard 1.20.1-2.3
	- curios 5.7.0+1.20.1
	- cyclopscore 1.19.0
	- dankstorage 8
	- darkmodeeverywhere 1.20.1-1.2.2
	- darkpaintings 17.0.4
	- darkutils 17.0.3
	- decorative_blocks 4.1.3
	- deep_aether 1.20.1-1.0.2
	- delightful 3.4.2
	- design_decor 0.3.0
	- diagonalblocks 8.0.2
	- diagonalfences 8.1.3
	- disenchanting 2.2.3
	- display_case 1.0.8
	- dramaticdoors 1.20.1-3.1.5
	- dummmmmmy 1.20-1.8.14
	- dustrial_decor 1.3.2
	- dyenamics 1.20.1-3.0.1
	- dynamiclightsreforged 1.20.1_v1.6.0
	- easy_emerald 1.4.15
	- easy_piglins 1.20.1-1.0.1
	- easy_villagers 1.20.1-1.0.17
	- easyanvils 8.0.1
	- easymagic 8.0.1
	- ecologics 2.2.0
	- elevatorid 1.20.1-lex-1.9
	- elytraslot 6.3.0+1.20.1
	- embeddium 0.3.4+mc1.20.1
	- embeddium_extra 0.5.4+mc1.20.1-build.116
	- enchantinginfuser 8.0.2
	- enchdesc 17.0.13
	- ensorcellation 5.0.0
	- entityculling 1.6.2
	- epherolib 0.1.2
	- estrogen 4.1.0+1.20.1-forge
	- everycomp 1.20-2.6.33
	- exchangers 1.20.1-3.5.1
	- expandability 9.0.0
	- explorerscompass 1.20.1-1.3.3-forge
	- fairylights 7.0.0
	- fallingleaves 2.1.0
	- fallingtree 4.3.4
	- farmersdelight 1.20.1-1.2.4
	- fastbench 8.0.4
	- fastfurnace 8.0.1
	- fastleafdecay 31
	- fastload 3.4.0
	- fastsuite 5.0.1
	- ferritecore 6.0.1
	- flib 0.0.11
	- flywheel 0.6.10-7
	- forge 47.2.20
	- forgeconfigscreens 8.0.2
	- fpsreducer 1.20-2.5
	- framedblocks 9.1.6
	- framework 0.6.26
	- friendsandfoes 2.0.9
	- ftblibrary 2001.1.5
	- ftbultimine 2001.1.4
	- fuelgoeshere 1.20.0-1.0.1
	- fusion 1.1.0c
	- gamemenumodoption 2.2.1
	- geckolib 4.4.2
	- gemsandcrystals 1.4.6-forge+1.20.1
	- geode_plus 1.2.4
	- goblintraders 1.9.3
	- guardvillagers 1.20.1-1.6.4
	- gunpowderlib 1.20.2-2.2.1
	- handcrafted 3.0.6
	- hearth_and_home 1.20.1-2.0.1
	- highlight 2.0.1
	- iceberg 1.1.18
	- immediatelyfast 1.2.10+1.20.4
	- imst 2.1.0
	- incontrol 1.20-9.2.1
	- industrialforegoing 3.5.14
	- industrialforegoingsouls 1.20.1-1.0.4
	- infinitybuttons 1.20.1-4.0.2
	- integratedcrafting 1.1.7
	- integrateddynamics 1.21.2
	- integrateddynamicscompat 1.21.2
	- integratedterminals 1.4.12
	- integratedterminalscompat 1.4.12
	- integratedtunnels 1.8.25
	- integratedtunnelscompat 1.8.25
	- ironchest 1.20.1-14.4.4
	- ironfurnaces 4.1.4
	- ironjetpacks 7.0.3
	- jade 11.8.0
	- jadeaddons 5.2.2
	- jearchaeology 1.20.1-1.0.3
	- jei 15.3.0.4
	- jei_mekanism_multiblocks 4.2
	- jeresources 1.4.0.247
	- jukeboxfix 1.0.0+1.20.1
	- jumbofurnace 4.0.0.5
	- justenoughprofessions 3.0.1
	- justzoom 1.0.2
	- kambrik 6.1.1+1.20.1
	- kleeslabs 15.0.0
	- konkrete 1.8.0
	- kotlinforforge 4.10.0
	- lightoverlay 8.0.0
	- lootr 0.7.31.77
	- make_bubbles_pop 0.2.0-forge
	- maxhealthfix 12.0.2
	- mcef 2.1.4-1.20.1
	- mcwbridges 2.1.1
	- mcwdoors 1.1.0
	- mcwfences 1.1.1
	- mcwfurnitures 3.2.2
	- mcwlights 1.0.6
	- mcwpaintings 1.0.5
	- mcwpaths 1.0.4
	- mcwroofs 2.3.0
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.1
	- measurements 2.0.0
	- mekanism 10.4.5
	- mekanismadditions 10.4.5
	- mekanismgenerators 10.4.5
	- mekanismtools 10.4.5
	- mes 1.3-1.20-forge
	- metalbarrels 1.20.1-1
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- mining_dimension 1.20.1-1.1.0
	- mininggadgets 1.15.6
	- mixinextras 0.2.0-beta.9
	- mixinsquared 0.1.1
	- mns 1.0-1.20-forge
	- mob_grinding_utils 1.20.1-1.0.3
	- modernfix 5.13.0+mc1.20.1
	- moonlight 1.20-2.9.17
	- morered 4.0.0.4
	- mores 5.3.5-mc1.20.1
	- mousetweaks 2.25
	- mutil 6.1.1
	- mvs 4.1.1-1.20-forge
	- mysticalagradditions 7.0.2
	- mysticalagriculture 7.0.9
	- naturescompass 1.20.1-1.11.2-forge
	- netherportalfix 13.0.1
	- nethersdelight 1.20.1-4.0
	- nfm 2023.12.09
	- nightlights 1.1
	- nitrogen_internals 1.20.1-1.0.2-neoforge
	- nochatreports 1.20.1-v2.2.2
	- notenoughanimations 1.7.1
	- oculus 1.6.15a
	- overflowingbars 8.0.0
	- overweight_farming 1.20.1-2.1.0-forge
	- paragon 3.0.2
	- patchouli 1.20.1-84-FORGE
	- pickupnotifier 8.0.0
	- pigpen 15.0.2
	- pipez 1.20.1-1.2.6
	- placebo 8.6.1
	- playeranimator 1.0.2-rc1+1.20
	- plushies 1.4.0
	- pneumaticcraft 6.0.14+mc1.20.1
	- polyeng 0.1.0-1.20.1
	- polymorph 0.49.2+1.20.1
	- prism 1.0.5
	- puzzlesaccessapi 8.0.7
	- puzzlesapi 8.1.4
	- puzzleslib 8.1.17
	- quark 4.0-436
	- railways 1.5.3+forge-mc1.20.1
	- rechiseled 1.1.5c
	- rechiseledcreate 1.0.2
	- reeses_sodium_options 1.0.4
	- refinedpolymorph 0.1.0-1.20.1
	- refinedstorage 1.12.4
	- refinedstorageaddons 0.10.0
	- regions_unexplored 0.5.3.1
	- resourcefulconfig 2.1.2
	- resourcefullib 2.1.23
	- resourcify 1.3.1
	- rsrequestify 2.3.3
	- rubidium 0.7.1
	- runelic 18.0.2
	- sawmill 1.20-1.3.4
	- searchables 1.0.2
	- servercountryflags 1.9.3
	- simplemagnets 1.1.10
	- simplylight 1.20.1-1.4.6-build.50
	- sit 1.3.4
	- skinlayers3d 1.6.2
	- sliceanddice 3.2.0
	- smoothchunk 1.20.1-3.5
	- sophisticatedbackpacks 3.20.1.1012
	- sophisticatedcore 0.6.3.553
	- spark 1.10.53
	- spectrelib 0.13.15+1.20.1
	- stoneworks 8.0.0
	- storagedrawers 12.0.2
	- structory 1.3.4
	- structure_gel 2.16.0
	- stylisheffects 8.0.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.7.36
	- suppsquared 1.20-1.1.12
	- t_and_t 0.0NONE
	- taxfreelevels 1.3.9
	- tempad 2.3.3
	- terrablender 3.0.1.4
	- tetra 6.2.0
	- tetraextras 0.1.4-1.20.1
	- tetranomicon 1.5.3-1.20.1
	- tetrasdelight 1.20.1-1
	- tetratic_combat_expanded 2.7.1
	- textrues_embeddium_options 0.1.5+mc1.20.1
	- thermal 11.0.2
	- thermal_cultivation 11.0.0
	- thermal_dynamics 11.0.0
	- thermal_expansion 11.0.0
	- thermal_foundation 11.0.2
	- thermal_innovation 11.0.0
	- thermal_integration 11.0.0
	- thermal_locomotion 11.0.0
	- tipsmod 12.0.4
	- titanium 3.8.25
	- toms_storage 1.6.5
	- toolbelt 1.20.0
	- toolstats 16.0.7
	- torchmaster 20.1.5
	- tradingpost 8.0.2
	- trashcans 1.0.18b
	- tumbleweed 0.5.5
	- twigs 1.20.1-3.1.1
	- universalbonemeal 8.0.1
	- universalgrid 1.20.1-1.1
	- uppers 1.0.1
	- useitemonblockevent 1.0.0.2
	- vanillacookbook 2.2.2
	- visuality 2.0.2
	- waterdripsound 0.3.2
	- waystones 14.1.3
	- webdisplays 2.0.1-1.20.1
	- woodset_furniture 1.0.1
	- wstweaks 9.1.0
	- xaerominimap 23.9.7
	- xaeroworldmap 1.37.8
	- yeetusexperimentus 2.3.1-build.6+mc1.20.1
	- yungsapi 1.20-Forge-4.0.3
	- yungsbridges 1.20-Forge-4.0.3
	- yungsextras 1.20-Forge-4.0.3
	- zeta 1.0-13

**Comment by Daimon6453** [comment]
If you didn't already test it, I discovered that the culprit mod was "sawmill 1.20-1.3.4," by MehVahdJukaar.

**Comment by Daimon6453** [comment]
And after further testing, it turns out it's an issue with the latest version of Sawmill, so this is not a bug that pertains to Regions Unexplored.

**Comment by UHQ-GAMES** [comment]
thanks for checking into it for us!
