### ISSUE TITLE
Specialized farmland can't be planted on

### ISSUE THREAD

**Issue by DEAFG0AT** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#126]
**Describe the bug**
You can't plant crops on farmland blocks from this mod (forest dirt, plains dirt, etc.)

**How To Reproduce**
1. Till some Regions Unexplored dirt with a hoe.
2. Attempt to plant any vanilla or modded crop on new farmland.
3. Observe inability to do so.

**Version**
Minecraft Version: 1.19.2

Modloader Version: 0.4.25, API 0.77.0

Mod Version: 0.4.1

**Screenshots**

**Comment by KirboSoftware** [comment]
Will be on the backlog for the backport update for 1.19.2 fabric 👍
