### ISSUE TITLE
Server Crash with latest version 1.20.1 forge

### ISSUE THREAD

**Issue by vivagabe** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#129]
**Describe the bug**
Server Crashes on launch.

**Crash Logs**
[latest.log](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/14371699/latest.log)

**How To Reproduce**
Start server then crashes.

**Version**
Minecraft Version: 1.20.1

Modloader Version: Forge 47.2.0

Mod Version: (Forge 1.20.1) Regions Unexplored v0.5.4

**Screenshots**
n/a

Thanks!

**Comment by KirboSoftware** [comment]
Thanks for the report. I would have to pull down the forge versions, give me a couple minutes since @UHQ-GAMES gave me the wrong compiled jars....

**Comment by KirboSoftware** [comment]
fixed [here](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/commit/91f6e091d5ff15ebccc1cd13142962927afc2147). I will reupload the forge 1.20.1 version and please, do test.

**Comment by KirboSoftware** [comment]
it's being uploaded rn! 

https://modrinth.com/mod/regions-unexplored/version/HwRKKRvX
curseforge is under review rn
