### ISSUE TITLE
regions_unexplored:smouldering_woodland generation errors

### ISSUE THREAD

**Issue by iraThe56** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#13]
The regions_unexplored:smouldering_woodland biome sometimes generates in the ocean with no land. Otherwise, everything seems normal. This issue could potentially be related to the 'Terralith' mod as it is also installed.
**Version**
Minecraft Version:
1.19.2
Modloader Version:
forge 43.2.19
Modpack:
https://legacy.curseforge.com/minecraft/modpacks/rift-realms
Mod Version:
RegionsUnexploredForge-0.4.1_1+1.19.2.jar
**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/128321960/6238486a-98ff-4848-bcb4-7890cadb9895)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/128321960/6a3a4d1a-4a2d-4e8d-8daf-ed82db29153f)

**Comment by UHQ-GAMES** [comment]
yea sadly most likely terralith or some other terrain mod causing it, smouldering woodlands spawn in the exact same place as where a mushroom island should be
