### ISSUE TITLE
Breaking Cobalt Nylium gives Netherrack

### ISSUE THREAD

**Issue by CrystalZink** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#130]
**Describe the bug**
Okay so basically Cobalt Nylium, a block made of blackstone, gives you netherrack when broken

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.
no crash unga bunga

**How To Reproduce**
Steps to reproduce the bug:
break cobalt nylium

**Version**
Minecraft Version:
1.20.1 - Forge

Modloader Version:
47.2.20

Mod Version:
0.5.4

**Screenshots**

**Comment by UHQ-GAMES** [comment]
will fix for 0.5.5

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.5 06b1900b1a49e897e8c5d4fc7f9dee58b436359d
