### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Paxx3** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#136]
**Describe the bug**
There is a error in the logs. Just reporting it and the error is slowly spamming my log files. 

**Crash Logs**
Log: https://mclo.gs/zjqkSb6

There is no crash in the game.

**How To Reproduce**
Steps to reproduce the bug: Happening in the logs.

**Version**
Minecraft Version: 1.20.1

Modloader Version: Fabric 0.15.7

Mod Version: RegionsUnexploredFabric-0.5.4+1.20.1

**Screenshots**
https://prnt.sc/SslrMGb3yA-g

**Comment by UHQ-GAMES** [comment]
sadly this seems to be in issue cause by something else as it works fine on its own

**Comment by UHQ-GAMES** [comment]
made a small optimization to the loot tabel in 13edeeab0061531f96e27e525b880df1e759f3b8 , will close for now and pin it
