### ISSUE TITLE
Bug Report - mauve wall sign crash

### ISSUE THREAD

**Issue by Saliaam** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#14]
[crash-2023-08-02_18_55_30-client.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12242246/crash-2023-08-02_18_55_30-client.txt)
[tl-logger12043334126333834556.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12242247/tl-logger12043334126333834556.txt)
**Describe the bug**
There is an issue on Fabric version. Didnt find it's repo, so Im writing here. On sign from your mod probably causing crashes on server. I guess it is mauve wall sign. The problem is that if you try to relog on server after it you will be immideatly kicked with crash, so its hard to fix.

**How To Reproduce**
Steps to reproduce the bug: place mauve wall sign on a grass block. 

**Version**
Minecraft Version: 1.19.2 Fabric

Modloader Version: 0.14.21

Mod Version: 0.4+1.19.2

**Screenshots**

**Comment by IamForsaken** [comment]
I am also having the same issue, its any of the signs. Simply placing it you will crash. My guess is it's conflicting with another mod but i'm not sure which one. Rest of the mod seems to be working just fine though. Easy fix for a server is just to run the /remove or /setblock <coords> minecraft:air to remove the block. 

[crash-2023-08-06_15.59.40-client.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12270836/crash-2023-08-06_15.59.40-client.txt)
[tl-latest.log](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12270841/tl-latest.log)

**Comment by UHQ-GAMES** [comment]
sorry bout the delay, i believe this is fixed for 0.5.0, ill confirm with the fabric devs

**Comment by JoostMSoftware** [comment]
Heyo, an fabric maintainer here. @IamForsaken and @Saliaam have you 2 found out which mod causes the issue for you?

**Comment by IamForsaken** [comment]
@JoostMSoftware hi, ya it was the epic-knights.jar. once we removed that all our issues went away.

**Comment by JoostMSoftware** [comment]
Ahhh I see, I assume this is related to DarkRPG?
