### ISSUE TITLE
[Fabric 1.20.1 0.5.5] Prismarite is an armor trim material yet is unable to be applied to armor

### ISSUE THREAD

**Issue by Mieridduryn** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#140]
**Describe the bug**
Unsure if this is a true *bug* or just something that hasn't been fully implemented. Prismarite clusters [have the armor trim material tag](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/1.20.4/src/generated/resources/data/minecraft/tags/items/trim_materials.json) (and this shows up in REI), but cannot be applied to armor.

Prismarite clusters should be applicable as armor trims in some form or fashion. This is not possible as of the latest Fabric version of the mod.

**Crash Logs**
There is no crash and nothing relevant shows up in the logs.

**How To Reproduce**
Steps to reproduce the bug:
1. Obtain a Prismarite Cluster.
2. Obtain an armor trim template.
3. Attempt to apply the cluster to a piece of armor using that template in a Smithing Table.
4. Nothing will appear in the output slot.

Optional, if REI is installed: look at the recipes that use Prismarite clusters as input. It's supposedly applicable, presumably because it has the armor trim tag.

**Version**
Minecraft Version: 1.20.1

Modloader Version: Fabric 0.14.25

Mod Version: 0.5.5

**Screenshots**
![2024-03-07_20 08 20](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/155842515/f06a0435-4e56-41ae-b9c7-b74fb010eb99)
(Note: This mod is part of a modpack I like to play. Please ignore the background and the miscellaneous REI bookmarks. The weirdness with the armor trim was brought to my attention by another player of this pack.)

**Comment by UHQ-GAMES** [comment]
yea it was something i had wanted to implement but i couldnt get it to look the way i wanted it to so i never finished it, i'll either finish it or remove the tags in the future.
