### ISSUE TITLE
Cobalt Nylium not spreading

### ISSUE THREAD

**Issue by TrashKrab147** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#142]
**Describe the bug**
Cobalt Nylium does not spread to adjacent/nearby blackstone blocks. Only Cobalt Roots appear upon bonemeal interaction.

**Version**
Minecraft Version:  1.20.1

Modloader Version:  Fabric 0.15.7

Mod Version:  RegionsUnexploredFabric-0.5.5+1.20.1.jar

**Comment by TrashKrab147** [comment]
Not entirely sure if this even is a bug, if it isn't even supposed to spread, or it does and I just don't know how to spread it.

**Comment by UHQ-GAMES** [comment]
sadly this is a limitation of the blackstone block class, i could make it work but it would need a rework to work the same as the netherrack class, which might cause issues with other mods
