### ISSUE TITLE
Crash on forge 1.20.1

### ISSUE THREAD

**Issue by Marius-jj** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#144]
**Describe the bug**
Game crashed when exploring, now it crashes every time i load the save.

**Crash Logs**
https://pastebin.com/PASjw2Lk

**How To Reproduce**
Steps to reproduce the bug: Not sure

**Version**
Minecraft Version:
1.20.1

Modloader Version:
Forge 47.2.0
Mod Version:

**Screenshots**

**Comment by Liamgrayskull** [comment]
Seems to be caused by the dawn era- I'd refer this to the Sinytra Connector devs though,  likely an incompat there

**Comment by UHQ-GAMES** [comment]
duplicate issue here https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/147
