### ISSUE TITLE
[Fabric 1.20.1] [Compatibility Issue] Generation Issue

### ISSUE THREAD

**Issue by ghost** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#145]
-Bug-
Regions Unexplored seems to stop BetterNether from generating it's grass blocks.

(Issue does not crash the game)

-How to Reproduce-

1. Run Regions Unexplored with BetterNether 9.0.10
2. Go to the Nether

Version:1.20.1

Modloader Version:0.15.6

Mod Version:0.5.5

-Screenshot-
![2024-04-05_20 28 59](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/166193668/b14b74ff-3e60-4cc8-9d46-c0dcca539454)

>  _(Sorry if this is actually a BetterNether Issue and how it handles generation, and/or not the place for Fabric or compatibility reports. BetterNether is the only Nether generation mod I have tested to have this issue with Regions Unexplored)_

**Comment by UHQ-GAMES** [comment]
nope this is totally on our side, will have it fixed asap
