### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SNGMRSTARK** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#15]
**Describe the bug**
Wall signs when placed from this mod cause client to crash
**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.
[crash-2023-08-06_17.57.49-client.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12270845/crash-2023-08-06_17.57.49-client.txt)

**How To Reproduce**
Steps to reproduce the bug:
place any wall sign from Regions_unexplored
**Version**
Minecraft Version:
1.20.1
Modloader Version:
fabric 0.14.21
Mod Version:
RegionsUnexploredFabric-0.4.1+1.20.1.jar
**Screenshots**

**Comment by UHQ-GAMES** [comment]
i believe this is fixed for the next release but i will confirm with the fabric devs

**Comment by JoostMSoftware** [comment]
I assume this is using DarkRPG? @SNGMRSTARK If so, have you updated the modpack to the latest version?

**Comment by UHQ-GAMES** [comment]
this is being caused by another mod loading sign sheets too early, try using the latest version of puzzle lib since i saw it in your mod list
