### ISSUE TITLE
[1.20.1] Regions Unexplored breaks surface rules for other mods when Better Nether is installed

### ISSUE THREAD

**Issue by Reshy** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#153]
**Describe the bug**
Surface rules for all non-regions unexplored nether biomes seem to break when Better Nether is installed, even vanilla biomes.  I beleive this issue also happens in the Forge version using Connector with Better Nether.

Log:  https://pastebin.com/VDiPBZsc

**How To Reproduce**
Steps to reproduce the bug:
Mod Pack:
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/d5f85bfa-4bdf-4cb2-a051-97aef79076dd)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/77dcdcba-6446-4b5d-b779-cb695fe76d5c)

**Version**
Minecraft Version: 1.20.1

Modloader Version: 0.15.10

Mod Version: RegionsUnexploredFabric-0.5.5+1.20.1.jar

**Screenshots**
Without Regions Unexplored (Terra Blender, Incendium, Better Nether, Cinderscapes, etc.)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/498983be-aa96-4dbc-a149-e2a4832bc1cc)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/61b721dd-e975-43f2-aaa2-45230879cb6e)

With Regions Unexplored:
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/500e2066-cca7-475f-b2cb-e63d7e231c78)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/9edf898d-04a6-4aef-a007-f087f345d30d)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/860741e1-2170-4a22-9d01-c9ca548921f0)

Using Forge and Connector with the mentioned Mods causes the opposite issue to occur:
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/7e3a5d9a-62b0-4f80-ac79-b0ad5b0c84b2)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/589ace42-4cfd-4cd6-8a27-c40691721515)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/96b43acf-80f8-4e5b-960d-2da9acbdffcf)

**Comment by KirboSoftware** [comment]
There is currently a bug in general with regions unexplored and nether surface rules. So that checks out, fix is underway tho no ETA

**Comment by Bulldog83** [comment]
I've made a small mod for Fabric that fixes a problem
https://github.com/Bulldog83/RUNetherSurfaceRulesFix

**Comment by Reshy** [comment]
Ah that's nice to see.  It may be worth putting it on Modrinth or Curse so more than just the three of us can use it.

**Comment by Reshy** [comment]
> I've made a small mod for Fabric that fixes a problem https://github.com/Bulldog83/RUNetherSurfaceRulesFix

Stupid question but is there an already compiled Jar that can be used or is it a do it yourself sort of thing?

**Comment by UHQ-GAMES** [comment]
fixed in b329899d09f0b60de1e9774943cdc35c37b5121b
