### ISSUE TITLE
Dirt Path should not be tagged as dirt

### ISSUE THREAD

**Issue by WenXin20** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#154]
**Describe the bug**
Dirt paths are tagged as dirt, which means plants can be planted on the dirt paths, which shouldn't be possible.

**How To Reproduce**
- Create a path block
- Plant a flower on it

**Version**
Minecraft Version: 1.20.1

Modloader Version: Forge v47.2.20

Mod Version: 0.5.5

**Comment by UHQ-GAMES** [comment]
fixed in 9a9372a962358b6fc7025037d1b7409ff59ceaa9
