### ISSUE TITLE
Cyan Painted Planks Recipe Error

### ISSUE THREAD

**Issue by BiggShaneHere** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#155]
**Describe the bug**
Cyan Painted Planks are crafted using green dye instead of cyan dye

**How To Reproduce**
Steps to reproduce the bug:
1. Try crafting Cyan Painted Planks using cyan dye
2. Get nothing.

**Version**
Minecraft Version: 1.20.1

Modloader Version: Forge - 47.2.0

Mod Version: Regions Unexplored 0.5.5

**Screenshots**
![2024-05-06_14 33 15](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/155410604/3f7fe37a-5aef-4223-9459-1f8757bfa166)
![2024-05-06_14 33 19](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/155410604/f729111c-bbf4-48b3-80f7-c295dc889cdd)

**Comment by UHQ-GAMES** [comment]
fixed in 01a7dc545461e70bd04e98ac78e29a17a48b704f
