### ISSUE TITLE
Leaves are pushable by piston and conduct redstone

### ISSUE THREAD

**Issue by SilverDavidMC** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#156]
Edit: I meant that it conducts redstone, not that it suffocates. Got tired and mixed up.

**Describe the bug**
This is two in one. Leaves from this mod can be pushed by pistons, ~~and also cause suffocation to mobs inside of them.~~ and conduct redstone.

**How To Reproduce**
Push a leaf block from this mod with a piston. It should destroy the leaves, but instead they get pushed. This affects tree farms with leaf crusher systems.

~~Put an entity's head inside leaf blocks. The leaves should not cause suffocation, but they do. Visible in survival while riding a horse and having your head clip into the leaves.~~

**Version**
Minecraft Version: 1.20.4

Mod Version: 0.5.5

**Comment by UHQ-GAMES** [comment]
fixed in dc1ed11761997b50313f673aea4a5e95bdaf2d4d
