### ISSUE TITLE
[Fabric] Bugged Advancement Tab Texture

### ISSUE THREAD

**Issue by ItzLucaGER** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#158]
**Describe the bug**
Advancement tab has bugged texture

Minecraft Version:
1.20.1

Modloader Version:
0.92.1+1.20.1

Mod Version:
0.5.5

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/114831048/0e31583d-5d73-4997-8b8c-40bb7bb02a9d)

**Comment by KirboSoftware** [comment]
I keep forgetting this bug exists, thanks for reporting 👍 will add it to the planned fixes

**Comment by ItzLucaGER** [comment]
Oh damn, didnt think it was actually a bug with the mod but instead me being stupid with resourcepacks again :D Good to know

**Comment by KirboSoftware** [comment]
This issue is fixed and is added to the upcoming patch :+1:

**Comment by ItzLucaGER** [comment]
very nice
