### ISSUE TITLE
Dynmap textures not loading

### ISSUE THREAD

**Issue by AirsoftZajda** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#159]
**Describe the bug**
Hello i Have a prolbem, i ahve modded server on fabric with some mods, dynmap and regions unexplored, but the new biomes on dynmap are not loading, the blocks are just black. Any tips ?

**Version**
Minecraft Version: 1.20.1 Fabric

**Comment by AirsoftZajda** [comment]
> **Describe the bug** Hello i Have a prolbem, i ahve modded server on fabric with some mods, dynmap and regions unexplored, but the new biomes on dynmap are not loading, the blocks are just black. Any tips ?
> 
> **Version** Minecraft Version: 1.20.1 Fabric

**Comment by AirsoftZajda** [comment]
.

**Comment by KirboSoftware** [comment]
Hey, is this resolved? Just got to see this issue and wanted to query about the status of it

**Comment by PEKA75** [comment]
I have currently the exact same issue but i am using forge version... DynMap BlocScan doesn't seem to work.
