### ISSUE TITLE
Kapok tree wont grow?

### ISSUE THREAD

**Issue by lunagrave310** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#160]
Kapok sapling wont grow with sapling????

Tried to build a house using a kapok tree on a server but the sapling wont grow into the tree. tried it in singleplayer and still wouldn't work.

forge 1.20.1
 "RegionsUnexploredForge-0.5.5+1.20.1.jar"

**Comment by UHQ-GAMES** [comment]
the Kapok tree need to be planted in a plus pattern with 5 saplings, hoping to add tooltips in the future
