### ISSUE TITLE
Add french language

### ISSUE THREAD

**Issue by Gwen-Del** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#161]
I give you a French translation file.
It was made in version 0.5.3 of the mod, with minecraft 1.19.2

[fr_fr.json](https://github.com/user-attachments/files/15570168/fr_fr.json)

**Comment by KirboSoftware** [comment]
could you perhaps make a pull request for this so we can merge it in the code?

**Comment by Gwen-Del** [comment]
https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/pull/162
