### ISSUE TITLE
Keybindings no longer work

### ISSUE THREAD

**Issue by xHakaiii** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#165]
For some reason when i put this mod in my modpack, makes my d button not work, and makes my jump command set to default key (space) , the games no longer follows commands input that i set in the keybindings part

it doesnt crash the game tho.

**How To Reproduce**
I cant find the mod that conflicts with this
**Version**
Minecraft Version: 1.19.2

Modloader Version: Fabric 0.15.11

Mod Version: 1.19.2

**Comment by KirboSoftware** [comment]
We don't modify the keybindings 🤔 and you're 100% that's happening because of regions?
