### ISSUE TITLE
[Fabric BCLib Incompatibility] Vanilla Biomes Don't Generate Properly with Regions Unexplored + BetterNether 

### ISSUE THREAD

**Issue by Verdigris7** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#166]
Version 1.20.1

Modlist:
BCLib 3.0.14
Better Nether 9.0.10
TerraBlender 3.0.1.7
Regions Unexplored (Fabric) 0.5.5+1.20.1

Warped Forest, Crimson Forest, and Soul sand valley generate as nether wastes when these mods are installed together. The betternether old warped trees and crimson glow forest trees generate fine, but vanilla warped and crimson trees as well as the entire soul sand valley don't generate.

I tested without Regions Unexplored to see if it was a terrablender issue, generation was fine. I also tested with only BcLib/BetterNether installed and generation was still fine. 

Together, vanilla biomes look like this:

Crimson Forest
![2024-06-18_19 49 11](https://github.com/quiqueck/BetterNether/assets/140852966/181d9ba0-b684-4b05-9cc9-c51cfa9d8dd9)
Soul Sand Valley
![2024-06-18_19 50 12](https://github.com/quiqueck/BetterNether/assets/140852966/a77ec822-e7b2-4a2f-bd2d-b755b9969fa4)
![2024-06-18_19 50 17](https://github.com/quiqueck/BetterNether/assets/140852966/d14c8882-a8cc-4db6-8e31-2eb603d0009c)

UPDATE: 
I tested again with all the mods together without using the BetterX worldtype and vanilla biomes generated as they should, so it looks like BcLib is the cause.
To clarify, this isn't fixed. I was using BetterX worldtype previously, now with default world generation the vanilla biomes are spawning properly, with their BetterNether additions.

Crimson Forest
![2024-06-18_19 54 41](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/140852966/45d5d7c0-548d-4ade-bf5f-b285c9ad20e4)
Soul Sand Valley
![2024-06-18_20 12 01](https://github.com/quiqueck/BetterNether/assets/140852966/2eae2087-1a17-4df1-abd1-d20ae259ee50)

**Comment by Verdigris7** [comment]
I would close this, since BCLib compatibility isn't your guys' priority. I'll let you do the honors though, just in case whoever reads this can fix it.

**Comment by UHQ-GAMES** [comment]
added workaround in b329899d09f0b60de1e9774943cdc35c37b5121b
