### ISSUE TITLE
[Forge 1.20.1] External incompatibility breaks some textures

### ISSUE THREAD

**Issue by Krimatoria** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#169]
For some reason, some of the colors, depending on the position, are created with the missing texture. How do I figure out what the problem is?

> [04:45:02] [Worker-ResourceReload-6/INFO] [quark-zeta/]: Dispatching ForgeZAddModels (as ZAddModels) to 5 listeners
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model regions_unexplored:yellow_lupine#:
>     minecraft:textures/atlas/blocks.png:regions_unexplored:block/lupine_pink1
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:q/born_in_chaos_v1/hollow_scorched_log#axis=x,waterlogged=false:
>     minecraft:textures/atlas/blocks.png:born_in_chaos_v1:block/scorched_log_top
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model born_in_chaos_v1:great_reaper_axe#inventory:
>     minecraft:textures/atlas/blocks.png:born_in_chaos_v1:block/
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model lost_aether_content:gravitite_shield#inventory:
>     minecraft:textures/atlas/blocks.png:aether:block/enchanted_gravitite
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model bountiful:decree#inventory:
>     minecraft:textures/atlas/blocks.png:bountiful:item/decree
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model supplementaries:tater_in_a_jar#inventory:
>     minecraft:textures/atlas/blocks.png:quark:model/tiny_potato/default
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model regions_unexplored:pink_lupine#:
>     minecraft:textures/atlas/blocks.png:regions_unexplored:block/lupine_pink1
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model regions_unexplored:red_lupine#:
>     minecraft:textures/atlas/blocks.png:regions_unexplored:block/lupine_red1
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model regions_unexplored:purple_lupine#:
>     minecraft:textures/atlas/blocks.png:regions_unexplored:block/lupine_purple1
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model cataclysm:coral_chunk#inventory:
>     minecraft:textures/atlas/blocks.png:cataclysm:item/coral_chunk_1
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model lost_aether_content:zanite_shield#inventory:
>     minecraft:textures/atlas/blocks.png:aether:item/zanite_gemstone
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model regions_unexplored:blue_lupine#:
>     minecraft:textures/atlas/blocks.png:regions_unexplored:block/lupine_blue1
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:q/born_in_chaos_v1/hollow_scorched_log#axis=z,waterlogged=false:
>     minecraft:textures/atlas/blocks.png:born_in_chaos_v1:block/scorched_log_top
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:q/born_in_chaos_v1/hollow_scorched_log#axis=y,waterlogged=true:
>     minecraft:textures/atlas/blocks.png:born_in_chaos_v1:block/scorched_log_top
> [04:45:21] [Worker-ResourceReload-6/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:q/born_in_chaos_v1/hollow_scorched_log#inventory:

RegionsUnexploredForge-0.5.5+1.20.1.jar
![image](https://github.com/user-attachments/assets/2bd9ab09-f308-4d33-9dd0-c6aaa650cec1)

**Comment by UHQ-GAMES** [comment]
not sure whats going on here but it works correctly on its own so something must be making a change that breaks it

**Comment by Krimatoria** [comment]
> не уверен, что здесь происходит, но само по себе оно работает правильно, так что что-то должно вносить изменения, которые его ломают

Yes, I found it, it was a resource pack - Ashen_Mod_Compatibility.zip
If you remove the resource pack, everything is fine)

**Comment by Krimatoria** [comment]
> not sure whats going on here but it works correctly on its own so something must be making a change that breaks it

I think the problem can be closed, I wrote to the Ashen developer

**Comment by UHQ-GAMES** [comment]
thanks for the heads up, feel free to let me know if anything changes and i can reopen
