### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by bluegamer22421** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#172]
**Describe the bug**
all the items in the mod are named item.Group.ru_main

**Crash Logs**
theres no crash logs

**How To Reproduce**
join a new world with mods: Amplified nether, Regions Unexplored, Biomes o plenty, WF caves overhaul, repurposed structures, terrablender forge all the last versions for 1.19.2

**Version**
Minecraft Version: 1.19.2 forge

Modloader Version: 43.4.2

Mod Version: Regions Unexplored v0.5.3

**Screenshots**
![screenshot12231](https://github.com/user-attachments/assets/c6707934-144a-4f2d-b617-872a5b7f8bfb)

**Comment by UHQ-GAMES** [comment]
this has been fixed in later versions, however 1.19.2 was discontinued before this fix was made
