### ISSUE TITLE
[1.21-NeoForge] Anything can be used as fuel and typical fuel(like coal) only smelts 0,5 items instead of 8.

### ISSUE THREAD

**Issue by Gbergz** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#174]
**Describe the bug**
Any items/blocks can be used as fuel and typical fuel(like coal) only smelts 0,5 items instead of 8.

**Crash Logs**
No crash.

**How To Reproduce**
Smelt anything valid with coal.
It only smelts 0,5 items.
Profit.

**How To Reproduce 2**
Smelt anything like Raw Iron with anything like a grass block.
Proceeds to smelt..
Profit.

**Version**
Minecraft Version: 1.21

Modloader Version: NeoForge 21.0.97

Mod Versions: 
regions_unexplored-neoforge-1.21-0.5.6
TerraBlender-neoforge-1.21-4.0.0.1

**Screenshots**
Video of issue: https://streamable.com/hu0taj

**Other Info**
I am only using Terrablender & Regions Unexplored, no other mods involved.

**Comment by KirboSoftware** [comment]
Neoforge issues should be reported on the multiloader page 

Which is located here: https://github.com/UHQ-GAMES-MODS/RegionsUnexplored

However, we shall take note of this issue :+1:

**Comment by Gbergz** [comment]
Whooops, I think the CurseForge project page issue link lead me here. Will do for future issue.

And great.

**Comment by Gbergz** [comment]
Thanks for the fix!
