### ISSUE TITLE
Magnolia Sign crashes breaks/crashes world

### ISSUE THREAD

**Issue by fakeaccount42060** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#175]
Minecraft Version 1.21
Fabric 0.16.0
Modversion 0.5.6

By placing a normal Magnolia sign and being in reach for it to be loaded it instantly crashes the game.

[crash-2024-07-27_21.38.49-client.txt](https://github.com/user-attachments/files/16401360/crash-2024-07-27_21.38.49-client.txt)

edit: could be multiple signs, after testing "Larch sign" also crashes the game.
edit2: ok so far every sign crashed the game. Probably some compatibility issue

**Comment by KirboSoftware** [comment]
Would you like to report this to our multiloader repo https://github.com/UHQ-GAMES-MODS/RegionsUnexplored? 

This one is only meant for forge :+1: However, this one is noted

**Comment by fakeaccount42060** [comment]
Oh damn sorry, didnt pay attention. Im just gonna copy it to the other one.
