### ISSUE TITLE
[Bug Report]: Tall sapling dupe.

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#18]
**Describe the bug**
When you place a tall sapling and break either the top or bottom half of the two part block, it breaks the other one separately and causes the sapling to dupe.

**Crash Logs**
Not really any logs.

**How To Reproduce**
Steps to reproduce the bug:
1. Place down a tall sapling
2. break the sapling
3. now you have two saplings

**Version**
Minecraft Version: 1.20.1

Modloader Version: Fabric

Mod Version: 0.4.1

**Screenshots**

**Comment by UHQ-GAMES** [comment]
this is a known issue, will be fixed in 0.5.0!

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.0+
