### ISSUE TITLE
crash on world creation

### ISSUE THREAD

**Issue by guyfingerguy** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#19]
every time i make a new world, it crashes a few seconds into creation. i'm not good at tech or coding, so i'm sorry for a bad description/stupidity

just start a new world with the mod installed

**Version**
Minecraft Version: 1.20.1

Modloader Version: forge 47.1.0

Mod Version: 0.5.0

[crash-2023-08-24_22.56.10-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12436062/crash-2023-08-24_22.56.10-server.txt)

**Comment by UHQ-GAMES** [comment]
this is a known isssue with terralith and ive reported it to terralith devs!

**Comment by guyfingerguy** [comment]
got it, thanks!
