### ISSUE TITLE
Feature Request: Translatable advancements

### ISSUE THREAD

**Issue by unroman** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#21]
**Describe your suggestion.**
  Ability to translate advancements into another language

**Additional context**
  ![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/75941881/f6280b71-d658-4a30-a871-6a8cbfe96fa8)

**Comment by UHQ-GAMES** [comment]
ohh i totally forgot about that, just release 0.5.1 so ill make sure to have that done for 0.5.2

**Comment by UHQ-GAMES** [comment]
actually will sneak that into 0.5.1!

**Comment by UHQ-GAMES** [comment]
Fixed in 0.5.1!
