### ISSUE TITLE
Crash using new update

### ISSUE THREAD

**Issue by ModifiedMC** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#25]
I crashed in the most recent update of the mod, my console said this right before it kicked me / server crashed 
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/88593730/756bf775-a680-43e9-a1c2-f011410a6b5f)

and it generated this crash report: 
[crash-2023-08-26_07.14.19-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12444790/crash-2023-08-26_07.14.19-server.txt)

It was in a cave below a chunk i frequented before the update, the crash log seems to reference blueprint.jar however that wasnt updated recently and i had no issues on the previous version (v4.2)

**Comment by UHQ-GAMES** [comment]
its a known issue with terralith, theres an order issue in one of their biomes. already reported to them

**Comment by ModifiedMC** [comment]
So is it not compat with teralilth in the current state? how can I fix my server? is a new world required?

**Comment by ModifiedMC** [comment]
fixed with new terralilth update released earlier today.
