### ISSUE TITLE
[1.20.1 Forge Crash] Server startup - world generation

### ISSUE THREAD

**Issue by MrKashew** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#26]
MC version 1.20.1
Forge 47.1.43
TerraBlender-forge-1.20.1-3.0.0.169
[crash-2023-08-28_01.07.58-server.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12452012/crash-2023-08-28_01.07.58-server.txt)

**Comment by UHQ-GAMES** [comment]
update your terralith to v2.4.5, that version fixes this crash

**Comment by MrKashew** [comment]
worked for me - thanks!
