### ISSUE TITLE
[1.20.1-Forge] When mod is active it causes certain machines from some mods to output items out of thin air. (Crafting Table too.)

### ISSUE THREAD

**Issue by Gbergz** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#27]
**Describe the bug**
When mod is active it causes certain machines from some mods to output items out of thin air, this also happens in the normal Crafting Table.

**Crash Logs**
Not a crash.

### It is all reproducable with just Regions Unexplored + the mods listed below.
**How To Reproduce** (The mods I've experienced this issue with is noted below.)
1. Install Regions Unexplored on Forge.
2. Install EnderIO, Cyclic & Snowy Spirit.
3. Place down a Crafting Table. Put any recipe in it, craft something. > Output slot is now always a Wreath from Snowy Spirit.
4. Place down a Sagmill from EnderIO, do any recipe in it. Watch it output Clippings from air when first recipe is done.
5. Place down a Solidification Chamber from Cyclic, do any recipe. Watch it output Biomass from air when first recipe is done.
6. Profit.

(Issue is gone when Regions Unexplored is removed.)

**Version**
Minecraft Version: 1.20.1
Forge Version: 47.1.3
Regions Unexplored Version: 0.5.1
EnderIO Version: 6.0.18-alpha
Cyclic Version: 1.12.4
Snowy Spirit: 2.2.4

**Screenshots**
![screen](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/26634554/b84c0f54-05b5-4fcc-a982-c10ca073e7c4)

**Comment by UHQ-GAMES** [comment]
can you send your latest log? may be a tag issue

**Comment by UHQ-GAMES** [comment]
found it, datagen is adding air blocks to the leaves tag for no apparent reason, will fix it for 0.5.2

**Comment by UHQ-GAMES** [comment]
fixed, will hopefully be available in the coming days
