### ISSUE TITLE
Updating to the latest version destroys my world

### ISSUE THREAD

**Issue by Quietlee** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#28]
**Describe the bug**

Updating from RegionsUnexploredFabric-0.4.1+1.20.1.jar to RegionsUnexploredFabric-0.5.1_02+1.20.1.jar completely breaks the world gen. A large portion of our spawn area consists of plains dirt with barley on it. After updating to the latest version this week all of the plains dirt disappears, leaving about 5 empty blocks on top of the underlying stone, the grass that would have been attached to the top layer of plains dirt is floating in the air and all of the structures (generated and player built) are all floating in the air where they used to be on plains dirt. 

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

I asked my hosting site to roll back my server so I don't have access to the log. The game didn't crash, your mod just ruined a large portion of my world.

**How To Reproduce**
Steps to reproduce the bug: Updating to the latest version RegionsUnexploredFabric-0.5.1_02+1.20.1.jar

**Version**
Minecraft Version: 1.20.1

Modloader Version: Fabric

Mod Version: RegionsUnexploredFabric-0.5.1_02+1.20.1.jar 

**Screenshots**

The xaero world map initially goes black on the areas that contain plains dirt, everything is in shadow. If I use the /brush smooth command on areas it will update the lighting in those areas but the plains dirt has completely disappeared, leaving only stone underneath where it sued to be.

**Comment by UHQ-GAMES** [comment]
this is because those blocks were renamed in this update and the game thinks they don't exist, so it just turns them to air. I believe you can use Blockswap mod to work around the issue by replacing the old blocks with the 0.5.0 equivalent on load. This is why I put the warning in the changelog for 0.5.0 as it is basically a fully remade update with a lot of breaking changes.

**Comment by Quietlee** [comment]
Couldn't you just leave the name as it was so that you don't break every
players world that were unfortunate enough to use your mod? This seems like
a lot of work and grief just for a simple name change.

**Comment by UHQ-GAMES** [comment]
I didn't like the names of the blocks so I felt they needed to be changed. That's why I put that warning about it in the 0.5.0 changelog and did it. Im sorry it damaged your world but mods generally don't update well and this update was a really big update that really changed almost everything.
