### ISSUE TITLE
Remove duplicate Cherry trees. Vanila added these. (Affects both Forge and Fabric.)

### ISSUE THREAD

**Issue by MagmaBro123** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#3]
**Describe your suggestion.**
Title. Vanilla added its own Cherry trees. Regions Unexplored's Cherry trees are unneeded.

**Additional context**
(This is a screenshot taken from Vanilla.)
![2023-06-14_14 23 58](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/51277766/ac832a58-8b4e-4b8c-94d6-1d799ba0e37e)

**Comment by UHQ-GAMES** [comment]
Our cherry trees will be renamed to Sakura trees and will get a dark red wood set in the next update, this one is purely a port of the old version to 1.20 for the time being

**Comment by UHQ-GAMES** [comment]
Trees renamed in 0.5.0

**Comment by MagmaBro123** [comment]
> Our cherry trees will be renamed to Sakura trees and will get a dark red wood set in the next update, this one is purely a port of the old version to 1.20 for the time being

Oh, my bad then. Usually if a mod adds pink leaves it'll either be Sakura or Cherry, very confusing imo.
