### ISSUE TITLE
Feature Suggestion: Floating Islands

### ISSUE THREAD

**Issue by HoodBlah** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#30]
**Describe your suggestion.**
A floating islands preset like the one in this datapack.

https://modrinth.com/datapack/revamped-floating-islands

**Additional context**
Or a compatibility update so they work together.

**Comment by UHQ-GAMES** [comment]
looks pretty cool but terrain generation like this is sorta out of scope, as for compatibility, it would be up to the datapack dev to add the compat tag with terrablender
