### ISSUE TITLE
Bring Back Sculkwood!

### ISSUE THREAD

**Issue by Sw1ssCake** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#31]
So you're telling me you removed the BEST PART of the mod? Like it is not accurate to lore but how can you remove one of the best parts! I was planning to make a structure in there for my modpack but... Nope! You had to ruin the fun! It would of been a boss arena!!!
Really? Really devs?

P.S. Make Jeb Sheep spawn in the rainbow caves.

**Comment by UHQ-GAMES** [comment]
I removed the sculk stuff cause it felt lazy and i didnt like it anymore. i may add the woodset it back in a future update as end city loot or something (sapling in chests) but for now it will stay removed. And i actually like the idea of sheep maybe becoming rainbow if they eat prismoss, thanks for the suggestion!

**Comment by Sw1ssCake** [comment]
What if you put it in Ancient City chests and maybe a rare spawn in the deep dark with buried treasure underneath? Like echo shards and sculk blocks would fit.
