### ISSUE TITLE
Fabric 1.20.1 Crash when creating new world

### ISSUE THREAD

**Issue by Gamemassa** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#32]
**Describe the bug**
I tried to create a new SP World and my game crashed to desktop.

**Crash Logs**
Crash Report
(https://gist.github.com/Gamemassa/db4f4a151a71085742b2c1cfd81e7251)

Latest.log
https://gist.github.com/Gamemassa/d07215076bf289ce04441209b84e8b54

**Version**
Minecraft Version: 1.20.1

Modloader Version: Fabric 0.14.22

Mod Version: Regions Unexplored 0.5.1_02

**Comment by UHQ-GAMES** [comment]
update your terralith to the latest, that fixes this crash

**Comment by Gamemassa** [comment]
Yup, that fixed it. Thanks!

**Comment by UHQ-GAMES** [comment]
no problem!
