### ISSUE TITLE
Carnivorous Carr (biome idea)

### ISSUE THREAD

**Issue by Sw1ssCake** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#33]
I was wondering, 'What biome ideas would be horrible for a spawn?" I think I found the idea. Carnivorous Carr, a swampy biome filled with monstrous plants. Venus fly traps and pitcher plants would be the main flora. There would be rivers that run through the land, filled with dangerous kelp that would drag you down if you happen to swim over it. Holes filled with the acid of pitcher plants, burning you (and your hopes of having a good Minecraft experience) away in mere seconds. This biome would be not very fun to traverse, but rewarding to brave explorers. You will need Leather Boots to not become sluggish in this biome, but the plants can still bite you. The rewards would be found in the massive Acid Passage. If you jump down in the passage, you'll be faced with a dropper minigame, ending in a pool of pitcher acid. While you'll start to burn inside, you can find diamonds, gold blocks and iron blocks. Overall, this seems extremely unfun but that's the point! Hope this can get you inspired. 
(This is I'd expect it to look like, just with monstrous plants)
![Bruchwald_(Plauer_Stadtwald)](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/134797341/de2a73d3-8d99-4770-a2aa-ddbeab187c9e)

**Comment by Sw1ssCake** [comment]
When I say carnivorous plants, I mean stationary, not really new mobs; I know that's not your specialty.

**Comment by UHQ-GAMES** [comment]
definately a cool idea, may not be much space in the overworld but a cool idea that i will keep pinned... closing for now!
