### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SafeOfArsenal** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#34]
**Describe the bug**
you can walk through prismarite clusters and that doesn't make sense since u cant walk through amethyst ones

**Crash Logs**
dont have any

**How To Reproduce**
place a prismarite cluster down and attempt to stand on it

**Version**
Minecraft Version: 1.20.1

Modloader Version: Forge 47.1.47

Mod Version: v0.5.1

**Screenshots**

**Comment by UHQ-GAMES** [comment]
this is intentional as if they were solid it would be frustration to traverse the biome, so thats why i made it inconsistent with vanilla
