### ISSUE TITLE
Feature Suggestion: Wisteria Forest

### ISSUE THREAD

**Issue by SafeOfArsenal** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#35]
**Describe your suggestion.**
The Wisteria Forest would be a new magical forest biome. The trees would would be thin be packed together and maybe have some sort of moss hanging down from the leaves.

**Additional context**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/66153781/570d53d6-b7e1-4899-96f4-605877bca1ab)

Friends and Foes Compatibility
Mooblooms would spawn here

**Comment by OysterStew** [comment]
I second that ...

**Comment by UHQ-GAMES** [comment]
RU's overworld is a bit too crowded for any new woodsets right now, but definately a cool idea for elsewhere...

**Comment by UHQ-GAMES** [comment]
closing for now but will pin for future use!
