### ISSUE TITLE
Breaking a Magnolia boat drops a Baobab boat

### ISSUE THREAD

**Issue by DaddySpin** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#36]
**Describe the bug**
Breaking a Magnolia boat drops a Baobab boat

**How To Reproduce**
1. Break Magnolia boat
2. Baobab boat drops

**Version**
1.20.1

Modloader Version:
Forge 47.1.3

Mod Version:
0.5.2

**Comment by UHQ-GAMES** [comment]
thanks, ill look into it!
