### ISSUE TITLE
Andesite, granite, and diorite not being created

### ISSUE THREAD

**Issue by brianfreud** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#37]
I've used worldedit to doublecheck block distribution, in case I was just being really unlucky.  Using 1.20.1 with RegionsUnexploredForge-0.5.2+1.20.1, I get about 15% stone per chunk, about 5% tuff, and almost the entire remainder deepslate.  No andesite, granite, or diorite is being generated.  I'd love to use this mod, but the lack of andesite really hurts when trying to use it in conjunction with Create.

**Comment by UHQ-GAMES** [comment]
still looking into this, at least the mod on its own seems to be generating correctly
