### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SafeOfArsenal** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#39]
**Describe the bug**
So for you can place pink petals on clovers and it will totally replace the block (does not work the other way around) 

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

**How To Reproduce**
its pretty obvious

**Version**
Minecraft Version: 1.20.1

Modloader Version: 0.14.22 Fabric

Mod Version: 0.5.2

**Screenshots**

**Comment by UHQ-GAMES** [comment]
this is intentional, clover is replaceable like grass and fern blocks
