### ISSUE TITLE
TerraForged hates this mod's biomes.

### ISSUE THREAD

**Issue by MagmaBro123** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#41]
**Describe the bug**
Most if not all Regions Unexplored biomes (and cave biomes) do not generate within a TerraForged world.

You can find info on adding the biomes here: https://github.com/TerraForged/TerraForged/wiki/Mod:-Biomes.

**How To Reproduce**
Steps to reproduce the bug:
Create a world via the TerraForged mod's world type.

**Version**
Minecraft Version: 1.18.2. (Get TerraForged to update if this is too old.)
Modloader Version: Forge 42.2.10.
Mod Version: RegionsUnexploredForge-0.4.1_1+1.18.2.

**Screenshots**
(This is a BOP biome. Both BOP (besides cave biomes) and BYG (I think it adds cave biomes if I recall? If so, they most likely don't generate either) seem to generate just fine.)
![2023-09-26_13 38 39](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/51277766/6c4fd712-5d29-4205-bc20-4ab229d0e159)

**Comment by UHQ-GAMES** [comment]
sadly it would be up to terraforged to add support with this mod, or more likely support for terrablender

**Comment by SafeOfArsenal** [comment]
too bad that the creator of terraforged hasnt gone on curseforge since 2022

**Comment by MagmaBro123** [comment]
> too bad that the creator of terraforged hasnt gone on curseforge since 2022

ReTerraForged exists, see https://github.com/racoonman2/ReTerraForged.
