### ISSUE TITLE
Bug Report: Startup crash with Trails&Tales Backport

### ISSUE THREAD

**Issue by xFirefalconx** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#44]
**Describe the bug**
Game can't start, crashes

**Crash Logs**
please also see https://legacy.curseforge.com/minecraft/mc-mods/onetwenty-1-20-backport/issues/5

[latest.log](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12839400/latest.log)
[crash-2023-10-07_22.48.57-client.txt](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/12839401/crash-2023-10-07_22.48.57-client.txt)

**How To Reproduce**
Steps to reproduce the bug: Put both mods together and launch.

**Version**
Minecraft Version: 1.18.2

Modloader Version: Forge 40.2.10

Mod Version: 
RegionsUnexploredForge-0.4.1_1+1.18.2 
onetwenty-0.3.1-1.18.2
TerraBlender-forge-1.18.2-1.2.0.126.jar

**Screenshots**
N/A

**Comment by UHQ-GAMES** [comment]
sorry, as of now we dont update 1.18.2 any more. Sadly dont have time to update more versions than we already do
