### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Jannik44** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#45]
**Describe the bug**
There are some error messages in my server console you probably want to know about

**Crash Logs**
[13:11:30] [main/ERROR] [ne.me.ev.EveryCompat/]: Failed to generate recipe for q/regions_unexplored/sculkwood_post: recipe template returned null

**Version**
Minecraft Version:
1.19.2

Mod Version:
latest 1.19.2

**Comment by UHQ-GAMES** [comment]
that would be an issue with EveryCompat not generating it correctly. Sadly nothing i can do to fix it
