### ISSUE TITLE
Boat with chest recipes are wrong

### ISSUE THREAD

**Issue by DaddySpin** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#47]
Pretty much all off the boat with chest recipes are wrong and require a plank and chest instead of a boat and chest.
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/34575655/112d35e7-c0d4-42c5-8796-638615f66f9e)

**Comment by KirboSoftware** [comment]
is this on fabric or forge?

**Comment by DaddySpin** [comment]
This is forge 1.20.1 latest

**Comment by KirboSoftware** [comment]
thank you! Will take a look at it 👍

**Comment by KirboSoftware** [comment]
I've confirmed the issue and this is a issue for both forge and fabric on 0.5.x 👍 Sorry for the delay! @UHQ-GAMES we gotta put this one on our todo.

**Comment by KirboSoftware** [comment]
This has been resolved and will be fixed in the upcoming release whenever that's happening 👍

**Comment by UHQ-GAMES** [comment]
closing issue as complete, fixed for 0.5.4 update (whenever that happens)
