### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by Niduin** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#48]
**Describe your suggestion.**
It would be nice if i can select a specific color for the Prismarites and Prismoss to place.

In the moment it placed the colours defined like a rainbow placed side by side.

**Comment by UHQ-GAMES** [comment]
I originally wanted to make that possible but it was impossible to do while keeping the rainbow colouring, which is the whole point of it.

**Comment by UHQ-GAMES** [comment]
might be something ill look into in a later release
