### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Teralitha** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#5]
Seguaro Cactus Tree doesnt have needles.  Meaning, it doesnt hurt you like other cactus do.

**How To Reproduce**
Steps to reproduce the bug:
1. Walk into a cactus tree
2. Observe that nothing happens

**Version**
Minecraft Version:
1.20.1
Mod Version:
Same

**Comment by UHQ-GAMES** [comment]
This isn't a bug, this is intentional as of now, may change in 0.5.0 but haven't gotten to that yet
