### ISSUE TITLE
[1.19.2] Crash with Terralith on World Generation in 0.5.3

### ISSUE THREAD

**Issue by Reshy** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#50]
**Describe the bug**
Regions Unexplored crashes when Terralith is installed.

**Crash Logs**
https://pastebin.com/ehjtJJ5T

**How To Reproduce**
Use this modpack
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/d6ae2e6f-d150-4bfe-a0dd-855a82a355fc)

**Version**
Minecraft Version:  1.19.2

Modloader Version: 43.2.20

Mod Version: RegionsUnexploredForge-0.5.3+1.19.2.jar

**Comment by UHQ-GAMES** [comment]
this seems to be the same issue in 1.20.1 version with terralith, i let the terralith devs know about it

**Comment by BlackAures1** [comment]
https://www.curseforge.com/minecraft/mc-mods/expanded-ecosphere Also the crash happens with this mod

**Comment by Nathanator9000** [comment]
Unfortunately I'm having the same issue with other generation mods. Hopefully the Terralith devs respond to it soon.

**Comment by UHQ-GAMES** [comment]
Terralith devs know about it and said it will be fixed with the next version 

https://github.com/Stardust-Labs-MC/Terralith/issues/57

**Comment by UHQ-GAMES** [comment]
> https://www.curseforge.com/minecraft/mc-mods/expanded-ecosphere Also the crash happens with this mod

this is probably the same order cycle they had with us in 1.20, ill report it to them but its best to report it to them yourself as well

**Comment by catter1** [comment]
The bug with Terralith should now be fixed in the newest version for 1.19.x: [v2.3.12](https://modrinth.com/mod/terralith/version/2.3.12)

**Comment by UHQ-GAMES** [comment]
> The bug with Terralith should now be fixed in the newest version for 1.19.x: [v2.3.12](https://modrinth.com/mod/terralith/version/2.3.12)

thanks @catter1 !

closing as complete in https://github.com/Stardust-Labs-MC/Terralith/issues/57
