### ISSUE TITLE
Red Maple Trees Dropping leaves.

### ISSUE THREAD

**Issue by Daihok41** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#51]
**Describe the bug**
The Red maple Trees are droping leaves rather then saplings when chopped down

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

**How To Reproduce**
Cut down a Red maple Tree

**Version**
Minecraft Version:
1.20.1

Modloader Version:

Fabric Loader  0.14.22

Mod Version:

0.5.31- 1.20.1

**Screenshots**

**Comment by UHQ-GAMES** [comment]
thanks, will fix for 0.5.4

**Comment by UHQ-GAMES** [comment]
doest seem to be present in up to date forge versions, will check out fabric later

**Comment by Daihok41** [comment]
Yea its on fabric version i listed under bug that was using fabric loader sorry if i didnt specify version.

**Comment by UHQ-GAMES** [comment]
no worries! you did mention fabric i was just testing on forge as well

**Comment by KirboSoftware** [comment]
Will work on this 👍 I will give a shout when it's fixed

**Comment by KirboSoftware** [comment]
@Daihok41 did you have other mods installed where you got this issue from?

**Comment by KirboSoftware** [comment]
fixed in 0.5.4
