### ISSUE TITLE
[1.19.2] issue with creative tab name

### ISSUE THREAD

**Issue by SafeOfArsenal** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#60]
**Describe the bug**
the regions unexplored creative tab having a funky looking name

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

**How To Reproduce**
Steps to reproduce the bug:
once your in the game with mod press e then the arrow at the top then govern over the regions unexplored tab

**Version**
Minecraft Version:
1.19.2

Modloader Version:
43.3.2

Mod Version:
0.5.3

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/66153781/3a74608b-8673-4172-a36c-b335b8f17ac0)

**Comment by UHQ-GAMES** [comment]
this is known and will be fixed in 0.5.4

**Comment by UHQ-GAMES** [comment]
fixed for 0.5.4 here 6f0ea7fae30a5c51a776466a5317f5cc04c1ae29
