### ISSUE TITLE
[1.19.2]  RegionsUnexploredForge-0.5.3+1.19.2.jar crash on world gen with Wythers

### ISSUE THREAD

**Issue by Reshy** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#61]
**Describe the bug**
The most recent version of Regions Unexplored is crashing when generating with Wythers OVerhauled Overworld.

**Crash Logs**
Crash:  https://pastebin.com/FZ8xeuvU
Log:  https://pastebin.com/UXfPsxK5

**How To Reproduce**
Steps to reproduce the bug:  
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/2096384/249286d9-613f-4f6d-862d-6c48777378f7)

**Version**
Minecraft Version:  1.19.2

Modloader Version:  43.2.20

Mod Version: 0.5.3

**Comment by UHQ-GAMES** [comment]
this is known and i reported it to them here https://github.com/Cristelknight999/Expanded-Ecosphere/issues/66

as its an issue on their end, just gotta wait for it to be fixed

**Comment by UHQ-GAMES** [comment]
look like that issue wasnt fixed so maybe ill just remove the feature in question to quick fix it in 0.5.4
