### ISSUE TITLE
[External issue] Rendering issues with Indium

### ISSUE THREAD

**Issue by Fusion-Flux** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#62]
**Describe the bug**
Mod causes massive rendering errors with sodium

**Crash Logs**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/71662169/33160ab4-3ac5-42a8-a64a-31a7b8648df9)

**How To Reproduce**
use sodium 4.10 with indium

**Version**
Minecraft Version: 1.20.1

Modloader Version: 0.14.22

Mod Version:
0.4.1 - 0.5.3

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/71662169/574b6a94-ee77-472b-80d8-f7e56a8f6205)

**Comment by UHQ-GAMES** [comment]
unfortunately this would mainly be on their side as this mod uses vanilla block model jsons

**Comment by KirboSoftware** [comment]
I will take a look at this 👍 and check it out

**Comment by KirboSoftware** [comment]
also @Fusion-Flux why are you still at sodium v0.4.10? shouldn't you just update to 0.5.3? And also, do you have the right version of indium installed for the right sodium release? As that also matters

**Comment by UHQ-GAMES** [comment]
closing as stale
