### ISSUE TITLE
Bug Report "Mod isn't registering their wood types properly"

### ISSUE THREAD

**Issue by litjohn50** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#63]
**Describe the bug**
Log spam when trying to find issues about other mods. 

**Crash Logs**
https://gist.github.com/litjohn50/44160e04e4a5e5480301bc8c50042d9e

**How To Reproduce**
Run region's unexplored with Supplementaries and moonlight. Read the log for spam of  " mod isnt registering their wood type properly"

**Version**
Minecraft Version:
1.20.1
Modloader Version:
47.1.3
Mod Version:
RegionsUnexploredForge-0.5.3+1.20.1.jar
supplementaries-1.20-2.6.17.jar
moonlight-1.20-2.8.56-forge.jar
**Screenshots**
refer to gist github for details

**Additional information:**
Trying to reduce the amount of errors I find in my modpack

**Comment by UHQ-GAMES** [comment]
this is odd, we are registering our wood types correctly, will look into it

**Comment by KirboSoftware** [comment]
This issue is also on Fabric. But not so bad as it would only complain about:
```
[08/11/2023 11:27:48 am] [Render thread/WARN] Failed to generate hanging sign extension texture for regions_unexplored:alpha. Could be that the target mod isnt registering their wood type properly
[08/11/2023 11:27:48 am] [Render thread/INFO] Generated runtime CLIENT_RESOURCES for pack Moonlight Mods Dynamic Assets (supplementaries) in: 158 ms
```
of which, makes sense. Since we don't have a wood type for `alpha`

**Comment by katubug** [comment]
Same issue here.

Here's the pastebin link: https://pastebin.com/DxTqJaRN

Supplementaries fails to generate a hanging sign texture for Alpha, and suggests the wood type might be registered incorrectly. I have no idea what that means, but MehVahdJukaar said I should report it, so here I am! I'm not sure how to fix this but I'm concerned it's related to a "resource reload failed" error I keep getting.

**Comment by KirboSoftware** [comment]
We are aware of this issue, and we will be working on a fix that should fix it :+1: Please be patient

**Comment by katubug** [comment]
Thanks for letting me know!
