### ISSUE TITLE
Chest Boats have incorrect crafting recipes

### ISSUE THREAD

**Issue by Numerosityy** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#64]
**Describe the bug**
Chest Boats are currently crafted with a wood plank and a chest- it should be a wooden boat with a chest.

**Version**
Minecraft Version: 1.20.1

Modloader Version: Fabric Latest Version to date

Mod Version: Latest Version to date

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/114539001/0fd8744c-b1df-4ef6-9c8b-0374435cd949)

**Comment by UHQ-GAMES** [comment]
this is known and will be fixed in 0.5.4 (whenever thats ready)

**Comment by UHQ-GAMES** [comment]
fixed for 0.5.4 here 0e04911aa7eac3f40a8b42316beae854d5b203b3
