### ISSUE TITLE
Feature Suggestion: A config or a separate mod to reenable wood types like sculkwood

### ISSUE THREAD

**Issue by SafeOfArsenal** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#66]
**Describe your suggestion.**
either a separate mod or a config option for the main mod that lets you bring back the old wood types instead of just fully removing them

**Comment by UHQ-GAMES** [comment]
I've already considered bringing it back in a separate mod, so far only time will tell

**Comment by UHQ-GAMES** [comment]
pinning for future use!
