### ISSUE TITLE
Wood doesn't work with Create saws

### ISSUE THREAD

**Issue by Gajus69** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#67]
When attempting to use a mechanical saw to saw logs or planks from Regions Unexplored mod it doesn't work. It just spits the item back out.

**Comment by KirboSoftware** [comment]
create combability needs to be worked on and adjusted which takes a bit of time sadly.

**Comment by Gajus69** [comment]
Do you have any plans of making it compatible any time soon? If not, do you
know any ways to temporarily make it work using KubeJS for example?

**Comment by Gajus69** [comment]
Fair enough! Great work on the mod though, it's definitely my favorite biome generation mod right now

**Comment by Gajus69** [comment]
fuck you bitch I made it myself

**Comment by KirboSoftware** [comment]
first of @Gajus69 no need to swear, secondly. It's uncalled for to send such a response 👍 Don't treat others on how you don't want to be treated.

**Comment by Gajus69** [comment]
Money spread lil bro, we’ll see then 🙏🙏🙏

**Comment by KirboSoftware** [comment]
What money? and no need to pull such a attitude towards someone 👍 Anyway, create fix has been planned for a while now. So no need to be so hostile 👍
