### ISSUE TITLE
Generated brimwood leaves are set to `persistent = true` and cannot decay

### ISSUE THREAD

**Issue by saltyseadoggo** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#68]
**Describe the bug**
The leaves on brimwood trees, both naturally generated and grown via saplings, have their `persistent` blockstate set to true, and thus, their leaves cannot decay. This makes them annoying to deal with in survival mode, as you have to break all the leaves manually. It also makes brimwood trees incompatible with Thermal Expansion's tree extractor if you were to make a custom recipe to let it extract fluid from them, as the tree extractor checks for leaves with `persistent = false` to determine if a tree is naturally generated or not.

**Crash Logs**
[latest.log](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13322989/latest.log)

**How To Reproduce**
- Create new world with Regions Unexplored and Terrablender loaded.
- Go to the Nether and find an Infernal Holt biome.
- Look at the brimwood leaves and press F3.
- Note the persistent blockstate being set to true.
- Break the tree's logs.
- Note that the leaves do not decay after any amount of time.

**Version**
Minecraft Version: 1.19.2

Modloader Version: Forge 43.2.8

Mod Version: 0.5.3

**Screenshots**
![2023-11-10_12 28 56](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/69029346/afa0959f-46bd-4325-a44f-2baa35bffe31)

**Comment by UHQ-GAMES** [comment]
this was intentional as the trees would get cut off by overhangs above, causing mass leaf decay. I will make them non persistent when I get around to fixing it

**Comment by UHQ-GAMES** [comment]
pinning for future use for fix as the entire feature needs to be remade
