### ISSUE TITLE
Bug Report: Floating inside the larch boat

### ISSUE THREAD

**Issue by SafeOfArsenal** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#70]
**Describe the bug**
your floating when sitting inside the larch boat

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

**How To Reproduce**
u sit in boat

**Version**
Minecraft Version: 1.20.1

Modloader Version: forge 47.1.3

Mod Version:  0.5.3

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/66153781/15eb953f-1887-4b99-bc87-ad150a47338d)

**Comment by UHQ-GAMES** [comment]
just found a solution for this, i may include it in 0.5.4 but its not a serious bug and 0.5.4 is almost ready so it may be added to the next fix release

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 4987b7c0ccfc1053da014a1febc364f06c7f9477
