### ISSUE TITLE
Acacia and Baobab Shrubs

### ISSUE THREAD

**Issue by RicoBiscuit** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#73]
Hi there, how i do grow these mentioned shrubs? I tried with bone meal but it didn't work, or no need?
And it seems they take time to grow

Thanks.

**Comment by UHQ-GAMES** [comment]
shrubs do not grow, they are for mostly decoration but can be crafted with 2 saplings and crafted into 2 saplings for use

**Comment by RicoBiscuit** [comment]
Ohh right! i noticed that exist their saplings, i had a few ones in my large messy chest. I though that only existed shrubs of that types of trees.

Also i tested the saplings and they worked. Thank you!

**Comment by UHQ-GAMES** [comment]
awesome!
