### ISSUE TITLE
Mauve Sapling growing with beehive.

### ISSUE THREAD

**Issue by KostromDan** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#74]
I think saplings growed to tree shouldnt have beehive.

**Comment by Sandriell** [comment]
Can do this with vanilla saplings that are grown near flowers.

https://minecraft.wiki/w/Bee_Nest#Post-generation

**Comment by UHQ-GAMES** [comment]
yea this is intentional behaviour
