### ISSUE TITLE
Feature Suggestion: 5.0 update backport to 1.18.2

### ISSUE THREAD

**Issue by SafeOfArsenal** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#75]
**Describe your suggestion.**
Describe you ideas in detail here.

**Additional context**
Add any pictures, screenshots, or other relevant information about the suggestion here.

**Comment by UHQ-GAMES** [comment]
sadly 1.18.2 will not be revisited and wont get the 0.5.0 updates
