### ISSUE TITLE
Bug - Silt/Peat Farmland do not accept seeds.

### ISSUE THREAD

**Issue by SolemnDeadrunner** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#76]
**Describe the bug**

Silt Farmland/Peat Farmland do not accept seeds, regardless of light level or moisture.

**How To Reproduce**

1. Grab either Silt Dirt or Peat Grass.
2. Till the Silt Dirt or Peat Grass with a hoe.
3. Place a seed onto the newly created farmland.

**Version**

Minecraft Version: Tested on 1.20.2

Modloader Version: Tested on  Fabric Foader 0.14.24-1.20.2

Mod Version: Tested on Regions Unexplored v.0.5.3 1.20.2

Additionally also tested with a barebones installation of only Fabric Loader 0.14.24-1.20.2 , Fabric API 0.90.7 for 1.20.2 , Regions Unexplored v.0.5.3 1.20.2 , TerraBlender 3.2.0.14 1.20.2

Also additionally tested on 1.20.1 with its most recent prerequisite mod versions on a barebones installation.

**Comment by KirboSoftware** [comment]
will be fixed in 0.5.4

**Comment by UHQ-GAMES** [comment]
fixed for 0.5.4 3c91bd6c4d2c9b0104d270dff05de4190cc0b275
