### ISSUE TITLE
Bug: owo Blackstone? You're wrong, it's Netherrack!

### ISSUE THREAD

**Issue by MinerB4** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#77]
**Bug**
Cobalt Nylium drops Netherrack instead of Blackstone

1. Mine Cobalt Nylium with the appropriate tool,
2. Drops Netherrack (despite Blackstone Texture).

**Versions**
Minecraft 1.20.1, Forge 47.2.6
Regions Unexplored 0.5.3

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/70791904/c1896c41-2106-420f-8627-294bf26b069f)

**Comment by UHQ-GAMES** [comment]
lol, already fixed for 0.5.4!
