### ISSUE TITLE
(Connector incompat) Terrestria incompatible with Regions Forge

### ISSUE THREAD

**Issue by KirboSoftware** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#80]
**Describe the bug**
A mixin priority issue. Should follow fabric in this case. 

**Crash Logs**
see https://github.com/Sinytra/Connector/issues/552

**How To Reproduce**
Use regions, connector and terrestria

**Version**
Minecraft Version:
1.20.1 and plausible further
Modloader Version:

Mod Version:

**Screenshots**

**Comment by gniftygnome** [comment]
I think this affects Fabric too?  In any case maybe you could make the `@Override` be an injector instead, like ours?

https://github.com/TerraformersMC/Terraform/blob/1.20.3/terraform-dirt-api-v1/src/main/java/com/terraformersmc/terraform/dirt/mixin/MixinEatGrassGoal.java#L33

**Comment by KirboSoftware** [comment]
yea, this affects fabric as well. I made this more in a "hacky" way. So I would need to fix when I have the time.

**Comment by KirboSoftware** [comment]
This issue is also related to #93. Mainly tracking for fixing
