### ISSUE TITLE
[Bug Report] Chestboat inventory disappearing

### ISSUE THREAD

**Issue by Konin-Sensei** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#84]
**Describe the bug**
The inventory in a chest boat disappears when the boat gets unloaded.

**Crash Logs**
Does not cause a crash

**How To Reproduce**
- Craft a boat with a chest in it.
- Put items into the inventory.
- Leave the area and allow the boat to unload.
- Return to the boat and check the inventory.

**Version**
Minecraft 1.20.1

Modloader Version:
Fabric 0.14.24

Mod Version:
0.5.3

I am playing in the [Fantasy MC Modpack](https://www.curseforge.com/minecraft/modpacks/fantasy-minecraft-fabric).
The bug only occurs with Chestboats added by Regions Unexplored and not in Vanilla ones.

**Screenshots**
Video Example: https://youtu.be/Ri3V6GYLJ5A

**Comment by KirboSoftware** [comment]
Do you have logs for this @Konin-Sensei like, any strange behaviors in the logs you noticed while this happened? Sorry for the late reply as well. This somehow flew under my radar

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 b2293867ed25ad9c55c85b58982b0098b5df32ec
