### ISSUE TITLE
[1.20.1] Mod Loading has failed; ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Sandriell** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#87]
**Describe the bug**
Game crashes during startup.

**Crash Logs**
https://gist.github.com/Sandriell/8151a770f8f4503b58606d512c16be0d

**How To Reproduce**
Load the game

**Version**
Minecraft Version: 1.20.1

Modloader Version: Forge 47.2.17

Mod Version: 0.5.3

**Screenshots**
![2023-12-22_11 04 05](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/10704907/c23da8fc-ca2b-4410-b98a-10ecfc05647b)

**Comment by UHQ-GAMES** [comment]
sadly im not 100% whats causing this here. things you can try is make sure your RU and dependencies, deleting its configs and restarting. If that doesnt work id try removing mods until you find the incompatibility.
