### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by espresso3** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#88]
**Describe your suggestion.**
Describe you ideas in detail here.
Hi,

I want you help in what the problem can sit more.
I do run a server from this mod and I think this is important for you. The 1.20.1 fabric versions cannot always with some mods from biomemods (betterend, betternether, terralith, terrestria, let's dos.) Actully I do if ''let's do mods'' away, is the same problem by world is making or find a biome in the server. Blocks do well work so I know, but the spawn from biomes, that is a bit stuck.
I think is good start a (server) world with betterend, betternether, terralith, terrestria and edited regions_unexplored. Chunky is better if you will see from files. Use /chunky radius 1000 or 2000 for find a biome form regions_unexplored and /chunky start. 
Blocks do work in texture with vanlia and with mods, that I see before in the server. 
Tip: If the client have a mod that change block that can the player see that tab, but cannot place that block, if the server don't have that mod.
**In the files see you some floveds biomes text, that is actully by crashs in world.** 
Some biomes haven't this problem, I am not sure about that, because was later crash the server. I think was ashen biome that well work, but I am not sure. 
I don't have more that file and swapblock mod, that cannot fix this problem, I have tried that and the server crash later.  
I hope this help much, where the problem more is and keep in your head that in server creative mode all tabs and blocks can find, also client-biomemod and the server don't have that.
**I want alone you give advise for helping, where the problem is.**
I wish to you merry christmas and happy new year.

**Additional context**
Add any pictures, screenshots, or other relevant information about the suggestion here.

**Comment by UHQ-GAMES** [comment]
I'm sorry I'm having trouble understanding what the issue you're having is. If you're having issues with the BetterX world types that would most likely be on their side since they make a lot of big changes to biome placement. If you have logs or can provide pictures of what you mean that would greatly help!
