### ISSUE TITLE
Prismoss dropping stone when broken

### ISSUE THREAD

**Issue by MarioSMB** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#90]
**Describe the bug**
Prismoss (regions_unexplored:prismoss) drops a stone block instead of cobblestone when broken with a regular pickaxe.

**Crash Logs**
N/A

**How To Reproduce**
Steps to reproduce the bug: N/A

**Version**
Minecraft Version: 1.20.1

Modloader Version: 47.2.17

Mod Version: 0.5.3+1.20.1

**Screenshots**
N/A

**Comment by MarioSMB** [comment]
This appears to be an issue with other blocks using stone as a base (verdant nylium etc) as well.

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 671a4d7770124a38e69ee288361a0bb1fcda2e94
