### ISSUE TITLE
Axes do not chop dead planks and their crafting recipes.

### ISSUE THREAD

**Issue by Ideriom** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#91]
**Describe the bug**
Using an axe on dead planks/any of the building items made out of them does not mine it faster; same speed as punching.

**Crash Logs**
Please add crash logs or latest logs to allow us to identify the error.

**How To Reproduce**
Steps to reproduce the bug:

**Version**
Minecraft Version: 1.19.2

Modloader Version: 43.3.0

Mod Version: 0.5.3

**Screenshots**

**Comment by UHQ-GAMES** [comment]
fix in 0.5.4 be0cdbef12a478a36291f429022dc9276d9ffd83
