### ISSUE TITLE
Minor Bug Report- Bioshroom block behavior

### ISSUE THREAD

**Issue by RechercheRaptor** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#92]
Minecraft version 1.19.2, forge version 43.3.5, mod version 0.5.3

At the moment bioshroom blocks don't have mining parity with other trees or mushrooms; the stems mine faster with an axe, but so far neither axes nor hoes seem to mine the actual blocks any faster, unlike vanilla mushrooms or fungi. I think this may also be connected to a minor incompatibility with Treeharvester (the Serilum mod, version 8.4), since at the moment bioshrooms seem to be the only mushroom/tree/fungus that can't be autoharvested with an axe right now (admittedly I haven't tested all of them; I've been trying to collect a lot of bioshroom blocks to bioluminesce my base so that's my main focus. I adore all of the awesome luminous blocks added by this mod, so the slower harvesting is still well worth it).

Also, is there a reliable way to get more regular bioshrooms? I've noticed that bioshroom blocks don't drop them (which is very convenient for collecting a lot of the actual blocks), but I didn't know if it was an oversight or intentional that they can only be gathered by exploring, what with the mod title and all :']

**Comment by UHQ-GAMES** [comment]
this was fixed for 0.5.4 in #53 and will be available in the next update!

**Comment by RechercheRaptor** [comment]
Awesome, thank you! :D
