### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Nathanator9000** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#93]
Game crashes upon launch when used with Immersive Weathering (Forge 1.20.1)

There was no crash report, but here is a launcher log.
[latest.log](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/files/13796250/latest.log)

Steps to reproduce the bug: Launch the game with moonlight lib, regions unexplored, and immersive weathering.

Minecraft Version: 1.20.1

Modloader Version: Forge 47.2.19

Mod Version: Regions Unexplored 0.5.3, Moonlight 2.8.78, Immersive Weathering 1.3.2

Additional Info: This issue has been posted on their page as well. Here is a link to that issue and the response from the author of Immersive Weathering.

https://github.com/AstralOrdana/Immersive-Weathering/issues/314

**Comment by KirboSoftware** [comment]
👍 Will look into it
