### ISSUE TITLE
Apple Oak Leaves do not decay after tree is cut down

### ISSUE THREAD

**Issue by matm616** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#94]
**Describe the bug**
Apple Oak Leaves generated as part of trees either in an Orchard biome or growing an Apple Oak Sapling do no decay after the tree is cutdown. I'm guessing this is related to https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/68

**Crash Logs**
Not crash causing

**How To Reproduce**
1. Find/grow tree with apple oak leaves
2. Cut down tree
3. Leaves remain

**Version**
Minecraft Version:
1.20.1

Modloader Version:
Forge 47.2.0

Mod Version:
RegionsUnexploredForge-0.5.3+1.20.1

**Screenshots**
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/35334792/b3e3f30c-7143-454a-bfce-0d10cc17df50)

**Comment by matm616** [comment]
Based off https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/9b08723d1f6bf818ad6ae8185656e8a009e4d01f/src/main/java/net/regions_unexplored/world/level/block/leaves/AppleLeavesBlock.java#L34
I would guess its not to do with the leaves being set to persistent but I'm not a modder so I'm not sure

**Comment by KirboSoftware** [comment]
we will take a look at it 👍

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 68c35c49f4fbb4a59b2e8a94666a0924f92d7d17
