### ISSUE TITLE
Regions Unexplored's silt and peat farmland doesn't allow Croptopia's crops

### ISSUE THREAD

**Issue by MagmaForce3400** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#95]
When I try to plant a crop from the mod croptopia on silt and peat farmland, it does nothing

Steps to reproduce the bug:
1 rightclick the silt or peat farmland with a crop from the mod croptopia
2 see that nothing happens

Minecraft Version:
1.19.2
Modloader Version:
forge 43.3.0
Mod Version:
RU 0.5.3 and Croptopia 2.2.2

**Comment by UHQ-GAMES** [comment]
thanks, this is a duplicate of #76 so ill close this one
