### ISSUE TITLE
The magnolia staircase is missing.

### ISSUE THREAD

**Issue by Krimatoria** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#96]
![2024-01-02_18 10 37](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/d0ed65a4-bb22-4d58-91fc-b8748532903c)

**Comment by KirboSoftware** [comment]
which modloader, mod version etc?

**Comment by UHQ-GAMES** [comment]
not sure if were talking about a different staircase but i can see magnolia stairs in your recipe book. sadly we cant help if you dont provide the information requested in the issue template

**Comment by Krimatoria** [comment]
It's not a ladder) This is the door) 

Forge 1.19.2 Version 43.3.7
jei-1.19.2-forge-11.6.0.1018
JustEnoughProfessions-forge-1.19.2-2.0.2
JustEnoughResources-1.19.2-1.1.0.179
RegionsUnexploredForge-0.5.3+1.19.2
TerraBlender-forge-1.19.2-2.0.1.166
Quark-3.4-418
AutoRegLib-1.8.2-55
moonlight-1.19.2-2.3.6-forge
everycomp-1.19.2-2.5.16

It was very difficult, but I found a way. There will be a lot of screenshots. Spoiler: The whole secret is in Quark+Every Compact. I added one mod each time to find a match. He was creating a new world on a superplane. When installing only the mod on Regions Unexplored, there are no stairs, in principle, not in one of the types of new wood, as it turned out, and chests. This can be seen in the screenshots below.

The Very Compact (Wood Good) mod by itself does not solve the problem here. There is an answer in the Quark mod (I attached a screenshot from CurseForge), it adds recipes for STAIRS for all types of wood. But by itself, the Quark mod without Every Compact cannot add a ladder recipe for Regions Unexplored. It's a little confusing, some kind of magic))) 

It's a pure coincidence when two mods do similar work in principle, but only together they create ladders and chests from Regions Unexplored. 

Quark+Every Compact+Regions Unexplored
I used Google Translate.

![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/6bf25cc3-bf8e-4535-b5c5-2c2662970f1e)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/c8d4dcc8-9f79-4f00-abec-5cba8c575fd3)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/8bbca544-a8c8-41c7-83f6-68349eb54fff)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/6dd59eea-0694-4fdb-b8ba-97ea43abf44c)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/2175ec14-52c9-4f3b-81d8-c880adec2611)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/4f5e3ab1-1dda-46a6-a3f9-f5c49955d328)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/624b304f-fbee-4f17-9ee6-8ff38f50abe6)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/fa72e9e0-32cc-4924-85c3-6633735deb34)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/826778a7-9d17-4cf5-a633-38cba27218dc)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/78b82bec-8c06-48e7-976a-a55e87d77474)
![image](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/106809386/a92a66cc-a682-44c2-84d9-366720e3a161)

**Comment by KirboSoftware** [comment]
So what you mean is that this would be an external suggestion/issue? Or how would I need to see this issue?

**Comment by Krimatoria** [comment]
> So what you mean is that this would be an external suggestion/issue? Or how would I need to see this issue?

Hmm. Well. If I understood you correctly:
1. Install Regions Unexplored Forge-0.5.3+1.19.2
There should be no ladders and chests in the new types of trees.
2. Moonlight-1.19.2-2.3.6- forge, Everycomp-1.19.2-2.5.16 (to see that it does not add new board recipes without Quark)
2. Install: Quark-3.4-418, AutoRegLib-1.8.2-55 
Ladders and chests will appear in Regions Unexplored Forge-0.5.3+1.19.2

I used these mods to view items:
jei-1.19.2-forge-11.6.0.1018
JustEnoughProfessions-forge-1.19.2-2.0.2
JustEnoughResources-1.19.2-1.1.0.179

**Comment by KirboSoftware** [comment]
As far as I remembered this is just a interaction that's with those mods as we on our own don't add custom variant wooden stuff. We cater towards more the vanilla stuff (vanilla's chest and ladders as example) over quark's chest's/ladder's
