### ISSUE TITLE
Alpha planks missing oak recipes

### ISSUE THREAD

**Issue by adozenlionsroaring** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#97]
**Describe the bug**
This is something I've noticed when using Regions Unexplored alongside compatibility mods like Every Compat (Wood Good) and Quark (currently in beta for 1.20.1). Every new wood type that RU adds is able to be crafted into a boat, a chest, etc - except for the Alpha planks. I suspect that they may not have been tagged properly as wood?

**Version**
Minecraft Version: 1.20.1
Modloader Version: Forge v47.2.0
Mod Version: v0.5.3

**Comment by UHQ-GAMES** [comment]
fixed in 0.5.4 ba5c2508c1c4e768057060cdb481f0efd6dd8306
