### ISSUE TITLE
Bug Report/Compatibility/Suggestion

### ISSUE THREAD

**Issue by grugsy** [UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE#99]
![2024-01-04_23 28 33](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/6725027/dabffaac-424c-43a6-9d59-408062f0c624)
![2024-01-04_23 31 12](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/assets/6725027/35c50bb4-7a22-4275-bb68-d27f344932e4)

Block light/colored light reflections vs no reflections/color. Would like to see all emissive/lightsources work with complimentary shaders+euphoria patches.

1.19.2 Fabric

**Comment by UHQ-GAMES** [comment]
sadly that compat would need to be added on the shaders side. because of how shaders work it needs to be added to the block properties in the shaderpack, which cant be done on the mod side
